// Nationalities list ordered by: Saudi Arabia first, then Arab countries, 
// then Muslim-majority countries, then rest alphabetically

export interface Nationality {
  code: string;
  name: string;
  name_ar: string;
}

// Saudi Arabia
const saudiArabia: Nationality = { code: "SA", name: "Saudi Arabia", name_ar: "المملكة العربية السعودية" };

// Arab Countries
const arabCountries: Nationality[] = [
  { code: "AE", name: "United Arab Emirates", name_ar: "الإمارات العربية المتحدة" },
  { code: "BH", name: "Bahrain", name_ar: "البحرين" },
  { code: "KW", name: "Kuwait", name_ar: "الكويت" },
  { code: "OM", name: "Oman", name_ar: "عُمان" },
  { code: "QA", name: "Qatar", name_ar: "قطر" },
  { code: "YE", name: "Yemen", name_ar: "اليمن" },
  { code: "IQ", name: "Iraq", name_ar: "العراق" },
  { code: "JO", name: "Jordan", name_ar: "الأردن" },
  { code: "LB", name: "Lebanon", name_ar: "لبنان" },
  { code: "SY", name: "Syria", name_ar: "سوريا" },
  { code: "PS", name: "Palestine", name_ar: "فلسطين" },
  { code: "EG", name: "Egypt", name_ar: "مصر" },
  { code: "SD", name: "Sudan", name_ar: "السودان" },
  { code: "LY", name: "Libya", name_ar: "ليبيا" },
  { code: "TN", name: "Tunisia", name_ar: "تونس" },
  { code: "DZ", name: "Algeria", name_ar: "الجزائر" },
  { code: "MA", name: "Morocco", name_ar: "المغرب" },
  { code: "MR", name: "Mauritania", name_ar: "موريتانيا" },
  { code: "DJ", name: "Djibouti", name_ar: "جيبوتي" },
  { code: "SO", name: "Somalia", name_ar: "الصومال" },
  { code: "KM", name: "Comoros", name_ar: "جزر القمر" },
];

// Muslim-Majority Countries (non-Arab)
const muslimMajorityCountries: Nationality[] = [
  { code: "PK", name: "Pakistan", name_ar: "باكستان" },
  { code: "BD", name: "Bangladesh", name_ar: "بنغلاديش" },
  { code: "ID", name: "Indonesia", name_ar: "إندونيسيا" },
  { code: "MY", name: "Malaysia", name_ar: "ماليزيا" },
  { code: "TR", name: "Turkey", name_ar: "تركيا" },
  { code: "IR", name: "Iran", name_ar: "إيران" },
  { code: "AF", name: "Afghanistan", name_ar: "أفغانستان" },
  { code: "UZ", name: "Uzbekistan", name_ar: "أوزبكستان" },
  { code: "KZ", name: "Kazakhstan", name_ar: "كازاخستان" },
  { code: "TM", name: "Turkmenistan", name_ar: "تركمانستان" },
  { code: "TJ", name: "Tajikistan", name_ar: "طاجيكستان" },
  { code: "KG", name: "Kyrgyzstan", name_ar: "قيرغيزستان" },
  { code: "AZ", name: "Azerbaijan", name_ar: "أذربيجان" },
  { code: "SN", name: "Senegal", name_ar: "السنغال" },
  { code: "ML", name: "Mali", name_ar: "مالي" },
  { code: "NE", name: "Niger", name_ar: "النيجر" },
  { code: "NG", name: "Nigeria", name_ar: "نيجيريا" },
  { code: "GM", name: "Gambia", name_ar: "غامبيا" },
  { code: "GN", name: "Guinea", name_ar: "غينيا" },
  { code: "SL", name: "Sierra Leone", name_ar: "سيراليون" },
  { code: "BF", name: "Burkina Faso", name_ar: "بوركينا فاسو" },
  { code: "TD", name: "Chad", name_ar: "تشاد" },
  { code: "MV", name: "Maldives", name_ar: "المالديف" },
  { code: "BN", name: "Brunei", name_ar: "بروناي" },
  { code: "XK", name: "Kosovo", name_ar: "كوسوفو" },
  { code: "AL", name: "Albania", name_ar: "ألبانيا" },
  { code: "BA", name: "Bosnia and Herzegovina", name_ar: "البوسنة والهرسك" },
];

// Rest of the World (alphabetically)
const restOfWorld: Nationality[] = [
  { code: "AR", name: "Argentina", name_ar: "الأرجنتين" },
  { code: "AM", name: "Armenia", name_ar: "أرمينيا" },
  { code: "AU", name: "Australia", name_ar: "أستراليا" },
  { code: "AT", name: "Austria", name_ar: "النمسا" },
  { code: "BY", name: "Belarus", name_ar: "بيلاروسيا" },
  { code: "BE", name: "Belgium", name_ar: "بلجيكا" },
  { code: "BZ", name: "Belize", name_ar: "بليز" },
  { code: "BJ", name: "Benin", name_ar: "بنين" },
  { code: "BT", name: "Bhutan", name_ar: "بوتان" },
  { code: "BO", name: "Bolivia", name_ar: "بوليفيا" },
  { code: "BW", name: "Botswana", name_ar: "بوتسوانا" },
  { code: "BR", name: "Brazil", name_ar: "البرازيل" },
  { code: "BG", name: "Bulgaria", name_ar: "بلغاريا" },
  { code: "BI", name: "Burundi", name_ar: "بوروندي" },
  { code: "KH", name: "Cambodia", name_ar: "كمبوديا" },
  { code: "CM", name: "Cameroon", name_ar: "الكاميرون" },
  { code: "CA", name: "Canada", name_ar: "كندا" },
  { code: "CV", name: "Cape Verde", name_ar: "الرأس الأخضر" },
  { code: "CF", name: "Central African Republic", name_ar: "جمهورية أفريقيا الوسطى" },
  { code: "CL", name: "Chile", name_ar: "تشيلي" },
  { code: "CN", name: "China", name_ar: "الصين" },
  { code: "CO", name: "Colombia", name_ar: "كولومبيا" },
  { code: "CG", name: "Congo", name_ar: "الكونغو" },
  { code: "CD", name: "Congo (DRC)", name_ar: "جمهورية الكونغو الديمقراطية" },
  { code: "CR", name: "Costa Rica", name_ar: "كوستاريكا" },
  { code: "CI", name: "Côte d'Ivoire", name_ar: "ساحل العاج" },
  { code: "HR", name: "Croatia", name_ar: "كرواتيا" },
  { code: "CU", name: "Cuba", name_ar: "كوبا" },
  { code: "CY", name: "Cyprus", name_ar: "قبرص" },
  { code: "CZ", name: "Czech Republic", name_ar: "جمهورية التشيك" },
  { code: "DK", name: "Denmark", name_ar: "الدنمارك" },
  { code: "DO", name: "Dominican Republic", name_ar: "جمهورية الدومينيكان" },
  { code: "EC", name: "Ecuador", name_ar: "الإكوادور" },
  { code: "SV", name: "El Salvador", name_ar: "السلفادور" },
  { code: "GQ", name: "Equatorial Guinea", name_ar: "غينيا الاستوائية" },
  { code: "ER", name: "Eritrea", name_ar: "إريتريا" },
  { code: "EE", name: "Estonia", name_ar: "إستونيا" },
  { code: "SZ", name: "Eswatini", name_ar: "إسواتيني" },
  { code: "ET", name: "Ethiopia", name_ar: "إثيوبيا" },
  { code: "FJ", name: "Fiji", name_ar: "فيجي" },
  { code: "FI", name: "Finland", name_ar: "فنلندا" },
  { code: "FR", name: "France", name_ar: "فرنسا" },
  { code: "GA", name: "Gabon", name_ar: "الغابون" },
  { code: "GE", name: "Georgia", name_ar: "جورجيا" },
  { code: "DE", name: "Germany", name_ar: "ألمانيا" },
  { code: "GH", name: "Ghana", name_ar: "غانا" },
  { code: "GR", name: "Greece", name_ar: "اليونان" },
  { code: "GT", name: "Guatemala", name_ar: "غواتيمالا" },
  { code: "GW", name: "Guinea-Bissau", name_ar: "غينيا بيساو" },
  { code: "GY", name: "Guyana", name_ar: "غيانا" },
  { code: "HT", name: "Haiti", name_ar: "هايتي" },
  { code: "HN", name: "Honduras", name_ar: "هندوراس" },
  { code: "HU", name: "Hungary", name_ar: "المجر" },
  { code: "IS", name: "Iceland", name_ar: "آيسلندا" },
  { code: "IN", name: "India", name_ar: "الهند" },
  { code: "IE", name: "Ireland", name_ar: "أيرلندا" },
  { code: "IL", name: "Israel", name_ar: "إسرائيل" },
  { code: "IT", name: "Italy", name_ar: "إيطاليا" },
  { code: "JM", name: "Jamaica", name_ar: "جامايكا" },
  { code: "JP", name: "Japan", name_ar: "اليابان" },
  { code: "KE", name: "Kenya", name_ar: "كينيا" },
  { code: "KP", name: "North Korea", name_ar: "كوريا الشمالية" },
  { code: "KR", name: "South Korea", name_ar: "كوريا الجنوبية" },
  { code: "LA", name: "Laos", name_ar: "لاوس" },
  { code: "LV", name: "Latvia", name_ar: "لاتفيا" },
  { code: "LR", name: "Liberia", name_ar: "ليبيريا" },
  { code: "LI", name: "Liechtenstein", name_ar: "ليختنشتاين" },
  { code: "LT", name: "Lithuania", name_ar: "ليتوانيا" },
  { code: "LU", name: "Luxembourg", name_ar: "لوكسمبورغ" },
  { code: "MG", name: "Madagascar", name_ar: "مدغشقر" },
  { code: "MW", name: "Malawi", name_ar: "ملاوي" },
  { code: "MT", name: "Malta", name_ar: "مالطا" },
  { code: "MX", name: "Mexico", name_ar: "المكسيك" },
  { code: "MD", name: "Moldova", name_ar: "مولدوفا" },
  { code: "MC", name: "Monaco", name_ar: "موناكو" },
  { code: "MN", name: "Mongolia", name_ar: "منغوليا" },
  { code: "ME", name: "Montenegro", name_ar: "الجبل الأسود" },
  { code: "MZ", name: "Mozambique", name_ar: "موزمبيق" },
  { code: "MM", name: "Myanmar", name_ar: "ميانمار" },
  { code: "NA", name: "Namibia", name_ar: "ناميبيا" },
  { code: "NP", name: "Nepal", name_ar: "نيبال" },
  { code: "NL", name: "Netherlands", name_ar: "هولندا" },
  { code: "NZ", name: "New Zealand", name_ar: "نيوزيلندا" },
  { code: "NI", name: "Nicaragua", name_ar: "نيكاراغوا" },
  { code: "MK", name: "North Macedonia", name_ar: "مقدونيا الشمالية" },
  { code: "NO", name: "Norway", name_ar: "النرويج" },
  { code: "PA", name: "Panama", name_ar: "بنما" },
  { code: "PG", name: "Papua New Guinea", name_ar: "بابوا غينيا الجديدة" },
  { code: "PY", name: "Paraguay", name_ar: "باراغواي" },
  { code: "PE", name: "Peru", name_ar: "بيرو" },
  { code: "PH", name: "Philippines", name_ar: "الفلبين" },
  { code: "PL", name: "Poland", name_ar: "بولندا" },
  { code: "PT", name: "Portugal", name_ar: "البرتغال" },
  { code: "RO", name: "Romania", name_ar: "رومانيا" },
  { code: "RU", name: "Russia", name_ar: "روسيا" },
  { code: "RW", name: "Rwanda", name_ar: "رواندا" },
  { code: "WS", name: "Samoa", name_ar: "ساموا" },
  { code: "SM", name: "San Marino", name_ar: "سان مارينو" },
  { code: "ST", name: "São Tomé and Príncipe", name_ar: "ساو تومي وبرينسيبي" },
  { code: "RS", name: "Serbia", name_ar: "صربيا" },
  { code: "SC", name: "Seychelles", name_ar: "سيشل" },
  { code: "SG", name: "Singapore", name_ar: "سنغافورة" },
  { code: "SK", name: "Slovakia", name_ar: "سلوفاكيا" },
  { code: "SI", name: "Slovenia", name_ar: "سلوفينيا" },
  { code: "SB", name: "Solomon Islands", name_ar: "جزر سليمان" },
  { code: "ZA", name: "South Africa", name_ar: "جنوب أفريقيا" },
  { code: "SS", name: "South Sudan", name_ar: "جنوب السودان" },
  { code: "ES", name: "Spain", name_ar: "إسبانيا" },
  { code: "LK", name: "Sri Lanka", name_ar: "سريلانكا" },
  { code: "SR", name: "Suriname", name_ar: "سورينام" },
  { code: "SE", name: "Sweden", name_ar: "السويد" },
  { code: "CH", name: "Switzerland", name_ar: "سويسرا" },
  { code: "TW", name: "Taiwan", name_ar: "تايوان" },
  { code: "TZ", name: "Tanzania", name_ar: "تنزانيا" },
  { code: "TH", name: "Thailand", name_ar: "تايلاند" },
  { code: "TL", name: "Timor-Leste", name_ar: "تيمور الشرقية" },
  { code: "TG", name: "Togo", name_ar: "توغو" },
  { code: "TO", name: "Tonga", name_ar: "تونغا" },
  { code: "TT", name: "Trinidad and Tobago", name_ar: "ترينيداد وتوباغو" },
  { code: "UG", name: "Uganda", name_ar: "أوغندا" },
  { code: "UA", name: "Ukraine", name_ar: "أوكرانيا" },
  { code: "GB", name: "United Kingdom", name_ar: "المملكة المتحدة" },
  { code: "US", name: "United States", name_ar: "الولايات المتحدة" },
  { code: "UY", name: "Uruguay", name_ar: "أوروغواي" },
  { code: "VU", name: "Vanuatu", name_ar: "فانواتو" },
  { code: "VA", name: "Vatican City", name_ar: "الفاتيكان" },
  { code: "VE", name: "Venezuela", name_ar: "فنزويلا" },
  { code: "VN", name: "Vietnam", name_ar: "فيتنام" },
  { code: "ZM", name: "Zambia", name_ar: "زامبيا" },
  { code: "ZW", name: "Zimbabwe", name_ar: "زيمبابوي" },
];

export const NATIONALITIES: Nationality[] = [
  saudiArabia,
  ...arabCountries,
  ...muslimMajorityCountries,
  ...restOfWorld,
];

export function getNationalityLabel(code: string | null | undefined, language: string = 'en'): string {
  if (!code) return '';
  const nationality = NATIONALITIES.find(n => n.code === code || n.name === code);
  if (!nationality) return code;
  return language === 'ar' ? nationality.name_ar : nationality.name;
}
