import { DateRange } from "react-day-picker";

export interface DashboardSectionsProps {
  t: any;
  dashboardLoading: boolean;
  dashboardData: any;
  laggingData: any;
  leadingData: any;
  responseData: any;
  peopleData: any;
  daysSince: number | null;
  periodComparison: any;
  getSparklineData: (key: any) => any[];
  trendData: any;
  trendLoading: boolean;
  getPeriodLabel: (period: string) => string;
  laggingLoading: boolean;
  leadingLoading: boolean;
  responseLoading: boolean;
  peopleLoading: boolean;
  startDate: Date;
  startDateStr: string;
  endDate: Date;
  endDateStr: string;
  branchId: string;
  locationLoading: boolean;
  locationData: any;
  reportersLoading: boolean;
  reporters: any;
  heatmapLoading: boolean;
  heatmapData: any;
  incidentTypeData: any;
  incidentTypeLoading: boolean;
  progressionData: any;
  progressionLoading: boolean;
  progressionUpdatedAt: number;
  progressionFetching: boolean;
  rcaData: any;
  rcaLoading: boolean;
  reporterBranchFilter: string;
  setReporterBranchFilter: (val: string) => void;
  locationBranchFilter: string;
  setLocationBranchFilter: (val: string) => void;
}
