import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import { useTheme } from "@/contexts/ThemeContext";
import {
  DocumentBrandingSettings,
  DocumentHeaderConfig,
  DocumentFooterConfig,
  DocumentWatermarkConfig,
  DEFAULT_DOCUMENT_SETTINGS,
  mapDbToDocumentSettings,
  mapSettingsToDb,
} from "@/types/document-branding";
import { toast } from "sonner";
import { useTranslation } from "react-i18next";

export function useDocumentBranding() {
  const { t } = useTranslation();
  const { profile } = useAuth();
  const { activeLogoUrl, tenantName } = useTheme();
  const queryClient = useQueryClient();
  const tenantId = profile?.tenant_id;

  // Fetch document settings for current tenant
  const {
    data: settings,
    isLoading,
    error,
  } = useQuery({
    queryKey: ["document-branding", tenantId],
    queryFn: async () => {
      if (!tenantId) return null;

      const { data, error } = await supabase
        .from("tenant_document_settings")
        .select("*")
        .eq("tenant_id", tenantId)
        .maybeSingle();

      if (error) throw error;

      // If no settings exist, return defaults with tenant info
      if (!data) {
        return {
          ...DEFAULT_DOCUMENT_SETTINGS,
          id: "",
          tenantId,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
        } as DocumentBrandingSettings;
      }

      return mapDbToDocumentSettings(data);
    },
    enabled: !!tenantId,
    staleTime: 5 * 60 * 1000, // Cache for 5 minutes
  });

  // Upsert mutation
  const updateMutation = useMutation({
    mutationFn: async (newSettings: Partial<DocumentBrandingSettings>) => {
      if (!tenantId) throw new Error("No tenant ID");

      const dbData = mapSettingsToDb(newSettings);
      dbData.tenant_id = tenantId;

      const { data, error } = await supabase
        .from("tenant_document_settings")
        .upsert(dbData as any, { onConflict: "tenant_id" })
        .select()
        .single();

      if (error) throw error;
      return mapDbToDocumentSettings(data);
    },
    onSuccess: (data) => {
      queryClient.setQueryData(["document-branding", tenantId], data);
      toast.success(t("documentSettings.saveSuccess"));
    },
    onError: (error) => {
      console.error("Failed to update document settings:", error);
      toast.error(t("documentSettings.saveError"));
    },
  });

  // Get formatted header config for document generators
  const getHeaderConfig = (): DocumentHeaderConfig => {
    return {
      logoUrl: settings?.showLogo ? activeLogoUrl : null,
      logoPosition: settings?.headerLogoPosition || "left",
      primaryText: settings?.headerTextPrimary || "HSSE Department",
      secondaryText: settings?.headerTextSecondary || null,
      backgroundColor: settings?.headerBgColor || "#ffffff",
      textColor: settings?.headerTextColor || "#1f2937",
      showLogo: settings?.showLogo ?? true,
    };
  };

  // Get formatted footer config for document generators
  const getFooterConfig = (): DocumentFooterConfig => {
    return {
      text: settings?.footerText || "Confidential - Generated by Dhuud Gatekeeper",
      showPageNumbers: settings?.showPageNumbers ?? true,
      showDatePrinted: settings?.showDatePrinted ?? true,
      backgroundColor: settings?.footerBgColor || "#f3f4f6",
      textColor: settings?.footerTextColor || "#6b7280",
    };
  };

  // Get formatted watermark config for document generators
  const getWatermarkConfig = (): DocumentWatermarkConfig => {
    return {
      text: settings?.watermarkText || null,
      enabled: settings?.watermarkEnabled ?? false,
      opacity: settings?.watermarkOpacity ?? 15,
    };
  };

  return {
    settings,
    isLoading,
    error,
    updateSettings: updateMutation.mutate,
    isUpdating: updateMutation.isPending,
    getHeaderConfig,
    getFooterConfig,
    getWatermarkConfig,
    tenantName,
    logoUrl: activeLogoUrl,
  };
}

// Standalone function to fetch document settings for use in generators
export async function fetchDocumentSettings(tenantId: string): Promise<DocumentBrandingSettings | null> {
  const { data, error } = await supabase
    .from("tenant_document_settings")
    .select("*")
    .eq("tenant_id", tenantId)
    .maybeSingle();

  if (error) {
    console.error("Failed to fetch document settings:", error);
    return null;
  }

  if (!data) return null;
  return mapDbToDocumentSettings(data);
}
