// Types for centralized document branding system

export type LogoPosition = 'left' | 'center' | 'right';

export interface DocumentBrandingSettings {
  id: string;
  tenantId: string;
  
  // Header Configuration
  headerLogoPosition: LogoPosition;
  headerTextPrimary: string;
  headerTextSecondary: string | null;
  headerBgColor: string;
  headerTextColor: string;
  showLogo: boolean;
  
  // Footer Configuration
  footerText: string;
  showPageNumbers: boolean;
  showDatePrinted: boolean;
  footerBgColor: string;
  footerTextColor: string;
  
  // Watermark
  watermarkText: string | null;
  watermarkEnabled: boolean;
  watermarkOpacity: number;
  
  // Timestamps
  createdAt: string;
  updatedAt: string;
}

export interface DocumentHeaderConfig {
  logoUrl: string | null;
  logoPosition: LogoPosition;
  primaryText: string;
  secondaryText: string | null;
  backgroundColor: string;
  textColor: string;
  showLogo: boolean;
}

export interface DocumentFooterConfig {
  text: string;
  showPageNumbers: boolean;
  showDatePrinted: boolean;
  backgroundColor: string;
  textColor: string;
}

export interface DocumentWatermarkConfig {
  text: string | null;
  enabled: boolean;
  opacity: number;
}

// Default settings for new tenants
export const DEFAULT_DOCUMENT_SETTINGS: Omit<DocumentBrandingSettings, 'id' | 'tenantId' | 'createdAt' | 'updatedAt'> = {
  headerLogoPosition: 'left',
  headerTextPrimary: 'HSSE Department',
  headerTextSecondary: null,
  headerBgColor: '#ffffff',
  headerTextColor: '#1f2937',
  showLogo: true,
  footerText: 'Confidential - Generated by Dhuud Gatekeeper',
  showPageNumbers: true,
  showDatePrinted: true,
  footerBgColor: '#f3f4f6',
  footerTextColor: '#6b7280',
  watermarkText: null,
  watermarkEnabled: false,
  watermarkOpacity: 15,
};

// Map database snake_case to camelCase
export function mapDbToDocumentSettings(dbRow: any): DocumentBrandingSettings {
  return {
    id: dbRow.id,
    tenantId: dbRow.tenant_id,
    headerLogoPosition: dbRow.header_logo_position || 'left',
    headerTextPrimary: dbRow.header_text_primary || 'HSSE Department',
    headerTextSecondary: dbRow.header_text_secondary,
    headerBgColor: dbRow.header_bg_color || '#ffffff',
    headerTextColor: dbRow.header_text_color || '#1f2937',
    showLogo: dbRow.show_logo ?? true,
    footerText: dbRow.footer_text || 'Confidential - Generated by Dhuud Gatekeeper',
    showPageNumbers: dbRow.show_page_numbers ?? true,
    showDatePrinted: dbRow.show_date_printed ?? true,
    footerBgColor: dbRow.footer_bg_color || '#f3f4f6',
    footerTextColor: dbRow.footer_text_color || '#6b7280',
    watermarkText: dbRow.watermark_text,
    watermarkEnabled: dbRow.watermark_enabled ?? false,
    watermarkOpacity: dbRow.watermark_opacity ?? 15,
    createdAt: dbRow.created_at,
    updatedAt: dbRow.updated_at,
  };
}

// Map camelCase to database snake_case for upsert
export function mapSettingsToDb(settings: Partial<DocumentBrandingSettings>): Record<string, any> {
  const result: Record<string, any> = {};
  
  if (settings.headerLogoPosition !== undefined) result.header_logo_position = settings.headerLogoPosition;
  if (settings.headerTextPrimary !== undefined) result.header_text_primary = settings.headerTextPrimary;
  if (settings.headerTextSecondary !== undefined) result.header_text_secondary = settings.headerTextSecondary;
  if (settings.headerBgColor !== undefined) result.header_bg_color = settings.headerBgColor;
  if (settings.headerTextColor !== undefined) result.header_text_color = settings.headerTextColor;
  if (settings.showLogo !== undefined) result.show_logo = settings.showLogo;
  if (settings.footerText !== undefined) result.footer_text = settings.footerText;
  if (settings.showPageNumbers !== undefined) result.show_page_numbers = settings.showPageNumbers;
  if (settings.showDatePrinted !== undefined) result.show_date_printed = settings.showDatePrinted;
  if (settings.footerBgColor !== undefined) result.footer_bg_color = settings.footerBgColor;
  if (settings.footerTextColor !== undefined) result.footer_text_color = settings.footerTextColor;
  if (settings.watermarkText !== undefined) result.watermark_text = settings.watermarkText;
  if (settings.watermarkEnabled !== undefined) result.watermark_enabled = settings.watermarkEnabled;
  if (settings.watermarkOpacity !== undefined) result.watermark_opacity = settings.watermarkOpacity;
  
  return result;
}
