/**
 * ROUTE REGISTRY - SINGLE SOURCE OF TRUTH
 * 
 * This file defines ALL pages in the system. Every page MUST be registered here.
 * 
 * Benefits:
 * - Routes are auto-generated from this registry
 * - Sidebar menu is auto-generated from this registry
 * - Build-time validation prevents orphan pages
 * - Database menu_items can be synced from this registry
 * 
 * Rules:
 * 1. EVERY page must have an entry here
 * 2. Hidden pages MUST have a hiddenReason
 * 3. menuCode must be unique
 * 4. path must be unique
 */

import { lazy } from "react";
import {
  LayoutDashboard,
  Shield,
  FileWarning,
  ClipboardCheck,
  Users,
  Settings,
  Settings2,
  Building2,
  Network,
  Layers,
  FolderTree,
  HelpCircle,
  LifeBuoy,
  CreditCard,
  Receipt,
  Puzzle,
  FileStack,
  BarChart3,
  ShieldAlert,
  ShieldCheck,
  FileCog,
  Package,
  List,
  Plus,
  QrCode,
  ClipboardList,
  Menu,
  Workflow,
  Clock,
  Radio,
  Calendar,
  MapPin,
  Briefcase,
  UserCheck,
  Route,
  Video,
  FileKey,
  HardHat,
  Map,
  AlertTriangle,
  Globe,
  Languages,
  GraduationCap,
  BookOpen,
  History,
  Bell,
  MessageSquare,
  FileText,
  User,
  Home,
  LogIn,
  UserPlus,
  Lock,
  Key,
  Smartphone,
  Download,
  Scale,
  Cookie,
  FileCheck,
  Undo2,
  Database,
  FileCode,
  Eye,
  Ticket,
  CheckCircle2,
  ScanLine,
  Wrench,
  HeartPulse,
  Calculator,
  DollarSign,
  Wallet,
  Camera,
  Search,
  Sparkles,
} from "lucide-react";
import type { RouteDefinition } from "./route-registry-types";
import { lazyWithRetry } from "@/lib/lazy-with-retry";

// Critical path pages - loaded immediately (imported directly in App.tsx)
// These are NOT in the registry for lazy loading but ARE registered for sidebar

// ============================================================================
// ROUTE REGISTRY
// ============================================================================

export const routeRegistry: RouteDefinition[] = [
  // -------------------------------------------------------------------------
  // PUBLIC ROUTES (No Auth Required)
  // -------------------------------------------------------------------------
  {
    path: "/invite",
    menuCode: "invite_gatekeeper",
    title: { en: "Welcome", ar: "مرحباً" },
    icon: LogIn,
    component: lazy(() => import("@/pages/InviteGatekeeper")),
    protection: "public",
    hidden: true,
    hiddenReason: "Entry point - not a navigable page",
  },
  {
    path: "/login",
    menuCode: "login",
    title: { en: "Login", ar: "تسجيل الدخول" },
    icon: LogIn,
    component: lazyWithRetry(() => import("@/pages/Login")),
    protection: "public",
    hidden: true,
    hiddenReason: "Auth page - not in sidebar",
  },
  {
    path: "/signup",
    menuCode: "signup",
    title: { en: "Sign Up", ar: "إنشاء حساب" },
    icon: UserPlus,
    component: lazyWithRetry(() => import("@/pages/Signup")),
    protection: "public",
    hidden: true,
    hiddenReason: "Auth page - not in sidebar",
  },
  {
    path: "/forgot-password",
    menuCode: "forgot_password",
    title: { en: "Forgot Password", ar: "نسيت كلمة المرور" },
    icon: Lock,
    component: lazyWithRetry(() => import("@/pages/ForgotPassword")),
    protection: "public",
    hidden: true,
    hiddenReason: "Auth page - not in sidebar",
  },
  {
    path: "/reset-password",
    menuCode: "reset_password",
    title: { en: "Reset Password", ar: "إعادة تعيين كلمة المرور" },
    icon: Key,
    component: lazyWithRetry(() => import("@/pages/ResetPassword")),
    protection: "public",
    hidden: true,
    hiddenReason: "Auth page - not in sidebar",
  },
  {
    path: "/install",
    menuCode: "install",
    title: { en: "Install App", ar: "تثبيت التطبيق" },
    icon: Download,
    component: lazy(() => import("@/pages/Install")),
    protection: "public",
    hidden: true,
    hiddenReason: "PWA install page - not in sidebar",
  },
  {
    path: "/mfa-setup",
    menuCode: "mfa_setup",
    title: { en: "MFA Setup", ar: "إعداد المصادقة الثنائية" },
    icon: Smartphone,
    component: lazyWithRetry(() => import("@/pages/MFASetup")),
    protection: "public",
    hidden: true,
    hiddenReason: "MFA setup flow - not in sidebar",
  },

  // Legal Pages
  {
    path: "/terms",
    menuCode: "terms_of_service",
    title: { en: "Terms of Service", ar: "شروط الخدمة" },
    icon: Scale,
    component: lazyWithRetry(() => import("@/pages/legal/TermsOfService")),
    protection: "public",
    hidden: true,
    hiddenReason: "Legal page - accessible via footer",
  },
  {
    path: "/privacy",
    menuCode: "privacy_policy",
    title: { en: "Privacy Policy", ar: "سياسة الخصوصية" },
    icon: Shield,
    component: lazyWithRetry(() => import("@/pages/legal/PrivacyPolicy")),
    protection: "public",
    hidden: true,
    hiddenReason: "Legal page - accessible via footer",
  },
  {
    path: "/cookies",
    menuCode: "cookie_policy",
    title: { en: "Cookie Policy", ar: "سياسة ملفات تعريف الارتباط" },
    icon: Cookie,
    component: lazyWithRetry(() => import("@/pages/legal/CookiePolicy")),
    protection: "public",
    hidden: true,
    hiddenReason: "Legal page - accessible via footer",
  },
  {
    path: "/acceptable-use",
    menuCode: "acceptable_use",
    title: { en: "Acceptable Use Policy", ar: "سياسة الاستخدام المقبول" },
    icon: FileCheck,
    component: lazyWithRetry(() => import("@/pages/legal/AcceptableUsePolicy")),
    protection: "public",
    hidden: true,
    hiddenReason: "Legal page - accessible via footer",
  },
  {
    path: "/refund-policy",
    menuCode: "refund_policy",
    title: { en: "Refund Policy", ar: "سياسة الاسترداد" },
    icon: Undo2,
    component: lazyWithRetry(() => import("@/pages/legal/RefundPolicy")),
    protection: "public",
    hidden: true,
    hiddenReason: "Legal page - accessible via footer",
  },
  {
    path: "/dpa",
    menuCode: "data_processing_agreement",
    title: { en: "Data Processing Agreement", ar: "اتفاقية معالجة البيانات" },
    icon: Database,
    component: lazyWithRetry(() => import("@/pages/legal/DataProcessingAgreement")),
    protection: "public",
    hidden: true,
    hiddenReason: "Legal page - accessible via footer",
  },
  {
    path: "/sla",
    menuCode: "service_level_agreement",
    title: { en: "Service Level Agreement", ar: "اتفاقية مستوى الخدمة" },
    icon: FileCode,
    component: lazyWithRetry(() => import("@/pages/legal/ServiceLevelAgreement")),
    protection: "public",
    hidden: true,
    hiddenReason: "Legal page - accessible via footer",
  },

  // Public Token-Based Pages
  {
    path: "/visitor-pass/:token",
    menuCode: "visitor_pass",
    title: { en: "Visitor Pass", ar: "بطاقة الزائر" },
    icon: Ticket,
    component: lazyWithRetry(() => import("@/pages/VisitorPass")),
    protection: "public",
    hidden: true,
    hiddenReason: "Token-based public page",
  },
  {
    path: "/visitor-badge/:token",
    menuCode: "visitor_badge",
    title: { en: "Visitor Badge", ar: "شارة الزائر" },
    icon: Ticket,
    component: lazyWithRetry(() => import("@/pages/VisitorBadgePage")),
    protection: "public",
    hidden: true,
    hiddenReason: "Token-based public page",
  },
  {
    path: "/worker-access/:token",
    menuCode: "worker_access",
    title: { en: "Worker Access", ar: "دخول العامل" },
    icon: UserCheck,
    component: lazyWithRetry(() => import("@/pages/WorkerAccessPass")),
    protection: "public",
    hidden: true,
    hiddenReason: "Token-based public page",
  },
  {
    path: "/worker-induction/:inductionId",
    menuCode: "worker_induction",
    title: { en: "Worker Induction", ar: "تعريف العامل" },
    icon: GraduationCap,
    component: lazyWithRetry(() => import("@/pages/WorkerInduction")),
    protection: "public",
    hidden: true,
    hiddenReason: "Token-based public page",
  },

  // -------------------------------------------------------------------------
  // PROTECTED ROUTES (Requires Auth)
  // -------------------------------------------------------------------------
  
  // Home & Dashboard
  {
    path: "/",
    menuCode: "home",
    title: { en: "Home", ar: "الرئيسية" },
    icon: Home,
    component: lazy(() => import("@/pages/Home")),
    protection: "protected",
    usesLayout: false,
    hidden: true,
    hiddenReason: "Home screen - special layout without sidebar",
  },
  {
    path: "/dashboard",
    menuCode: "dashboard",
    title: { en: "Dashboard", ar: "لوحة القيادة" },
    icon: LayoutDashboard,
    component: lazy(() => import("@/pages/Dashboard")),
    protection: "protected",
    sortOrder: 1,
  },
  {
    path: "/profile",
    menuCode: "profile",
    title: { en: "Profile", ar: "الملف الشخصي" },
    icon: User,
    component: lazyWithRetry(() => import("@/pages/Profile")),
    protection: "protected",
    hidden: true,
    hiddenReason: "User profile - accessed via header dropdown",
  },

  // -------------------------------------------------------------------------
  // HSSE EVENTS
  // -------------------------------------------------------------------------
  {
    path: "/incidents/dashboard",
    menuCode: "event_dashboard",
    title: { en: "Event Dashboard", ar: "لوحة الأحداث" },
    icon: BarChart3,
    component: lazyWithRetry(() => import("@/pages/incidents/HSSEEventDashboard")),
    protection: "hsse",
    parentCode: "hsse_events",
    sortOrder: 1,
  },
  {
    path: "/incidents",
    menuCode: "event_list",
    title: { en: "Event List", ar: "قائمة الأحداث" },
    icon: FileWarning,
    component: lazyWithRetry(() => import("@/pages/incidents/IncidentList")),
    protection: "protected",
    parentCode: "hsse_events",
    sortOrder: 2,
  },
  {
    path: "/incidents/report",
    menuCode: "report_event",
    title: { en: "Report Event", ar: "الإبلاغ عن حدث" },
    icon: FileWarning,
    component: lazyWithRetry(() => import("@/pages/incidents/IncidentReport")),
    protection: "protected",
    parentCode: "hsse_events",
    sortOrder: 3,
  },
  {
    path: "/incidents/:id",
    menuCode: "incident_detail",
    title: { en: "Incident Detail", ar: "تفاصيل الحادث" },
    icon: FileWarning,
    component: lazyWithRetry(() => import("@/pages/incidents/IncidentDetail")),
    protection: "protected",
    hidden: true,
    hiddenReason: "Dynamic route - accessed via incident list",
  },
  {
    path: "/incidents/investigate",
    menuCode: "investigation_workspace",
    title: { en: "Investigation Workspace", ar: "مساحة التحقيق" },
    icon: ClipboardCheck,
    component: lazyWithRetry(() => import("@/pages/incidents/InvestigationWorkspace")),
    protection: "hsse",
    parentCode: "hsse_events",
    sortOrder: 4,
  },
  {
    path: "/incidents/my-actions",
    menuCode: "my_actions",
    title: { en: "My Actions", ar: "إجراءاتي" },
    icon: ClipboardCheck,
    component: lazyWithRetry(() => import("@/pages/incidents/MyActions")),
    protection: "protected",
    parentCode: "my_actions",
    sortOrder: 1,
  },

  // -------------------------------------------------------------------------
  // INSPECTIONS & AUDITS
  // -------------------------------------------------------------------------
  {
    path: "/inspections/dashboard",
    menuCode: "inspection_dashboard",
    title: { en: "Inspection Dashboard", ar: "لوحة التفتيش" },
    icon: BarChart3,
    component: lazyWithRetry(() => import("@/pages/inspections/InspectionDashboard")),
    protection: "hsse",
    parentCode: "audits_inspections",
    sortOrder: 1,
  },
  {
    path: "/inspections/sessions",
    menuCode: "inspection_sessions",
    title: { en: "Inspection Sessions", ar: "جلسات التفتيش" },
    icon: ClipboardList,
    component: lazyWithRetry(() => import("@/pages/inspections/InspectionSessionsDashboard")),
    protection: "hsse",
    parentCode: "audits_inspections",
    sortOrder: 2,
  },
  {
    path: "/inspections/sessions/:sessionId",
    menuCode: "session_workspace",
    title: { en: "Session Workspace", ar: "مساحة الجلسة" },
    icon: ClipboardCheck,
    component: lazyWithRetry(() => import("@/pages/inspections/SessionWorkspace")),
    protection: "hsse",
    hidden: true,
    hiddenReason: "Dynamic route - accessed via session list",
  },
  {
    path: "/inspections/sessions/:sessionId/area",
    menuCode: "area_session_workspace",
    title: { en: "Area Session", ar: "جلسة المنطقة" },
    icon: ClipboardCheck,
    component: lazyWithRetry(() => import("@/pages/inspections/AreaSessionWorkspace")),
    protection: "hsse",
    hidden: true,
    hiddenReason: "Dynamic route - accessed via session",
  },
  {
    path: "/inspections/sessions/:sessionId/audit",
    menuCode: "audit_session_workspace",
    title: { en: "Audit Session", ar: "جلسة التدقيق" },
    icon: ClipboardCheck,
    component: lazyWithRetry(() => import("@/pages/inspections/AuditSessionWorkspace")),
    protection: "hsse",
    hidden: true,
    hiddenReason: "Dynamic route - accessed via session",
  },
  {
    path: "/inspections/schedules",
    menuCode: "inspection_schedules",
    title: { en: "Inspection Schedules", ar: "جداول التفتيش" },
    icon: ClipboardList,
    component: lazyWithRetry(() => import("@/pages/inspections/InspectionSchedules")),
    protection: "hsse",
    parentCode: "audits_inspections",
    sortOrder: 3,
  },
  {
    path: "/inspections/my-actions",
    menuCode: "my_inspection_actions",
    title: { en: "My Inspection Actions", ar: "إجراءات التفتيش الخاصة بي" },
    icon: ClipboardCheck,
    component: lazyWithRetry(() => import("@/pages/inspections/MyInspectionActions")),
    protection: "protected",
    parentCode: "audits_inspections",
    sortOrder: 4,
  },

  // -------------------------------------------------------------------------
  // SECURITY MODULE
  // -------------------------------------------------------------------------
  {
    path: "/security",
    menuCode: "security_dashboard",
    title: { en: "Security Dashboard", ar: "لوحة الأمن" },
    icon: LayoutDashboard,
    component: lazyWithRetry(() => import("@/pages/security/SecurityDashboard")),
    protection: "security",
    parentCode: "security",
    sortOrder: 1,
  },
  {
    path: "/security/access-control",
    menuCode: "access_dashboard",
    title: { en: "Access Dashboard", ar: "لوحة التحكم بالدخول" },
    icon: LayoutDashboard,
    component: lazyWithRetry(() => import("@/pages/security/AccessControlDashboard")),
    protection: "security",
    parentCode: "security",
    sortOrder: 2,
  },
  {
    path: "/security/gate-dashboard",
    menuCode: "gate_dashboard",
    title: { en: "Gate Operations", ar: "عمليات البوابة" },
    icon: Shield,
    component: lazyWithRetry(() => import("@/pages/security/GateGuardDashboard")),
    protection: "security",
    parentCode: "security",
    sortOrder: 3,
  },
  {
    path: "/visitors/register",
    menuCode: "visitor_register",
    title: { en: "Pre-Register Visitor", ar: "التسجيل المسبق للزائر" },
    icon: Plus,
    component: lazyWithRetry(() => import("@/pages/visitors/VisitorPreRegistration")),
    protection: "security",
    parentCode: "security",
    sortOrder: 4,
  },
  {
    path: "/visitors/list",
    menuCode: "visitor_list",
    title: { en: "Visitor Directory", ar: "دليل الزوار" },
    icon: List,
    component: lazyWithRetry(() => import("@/pages/visitors/VisitorList")),
    protection: "security",
    parentCode: "security",
    sortOrder: 5,
  },
  {
    path: "/security/blacklist",
    menuCode: "security_blacklist",
    title: { en: "Blacklist Management", ar: "إدارة القائمة السوداء" },
    icon: ShieldAlert,
    component: lazyWithRetry(() => import("@/pages/security/BlacklistManagement")),
    protection: "security",
    parentCode: "security",
    sortOrder: 6,
  },
  {
    path: "/security/patrols",
    menuCode: "patrol_dashboard",
    title: { en: "Patrol Dashboard", ar: "لوحة الدوريات" },
    icon: Network,
    component: lazyWithRetry(() => import("@/pages/security/PatrolDashboard")),
    protection: "security",
    parentCode: "security_patrols",
    sortOrder: 1,
  },
  {
    path: "/security/patrols/routes",
    menuCode: "patrol_routes",
    title: { en: "Patrol Routes", ar: "مسارات الدوريات" },
    icon: Route,
    component: lazyWithRetry(() => import("@/pages/security/PatrolRoutes")),
    protection: "security",
    parentCode: "security_patrols",
    sortOrder: 2,
  },
  {
    path: "/security/patrols/execute",
    menuCode: "execute_patrol",
    title: { en: "Execute Patrol", ar: "تنفيذ الدورية" },
    icon: Route,
    component: lazyWithRetry(() => import("@/pages/security/ExecutePatrol")),
    protection: "security",
    hidden: true,
    hiddenReason: "Action page - accessed via patrol dashboard",
  },
  {
    path: "/security/patrols/history",
    menuCode: "patrol_history",
    title: { en: "Patrol History", ar: "سجل الدوريات" },
    icon: Clock,
    component: lazyWithRetry(() => import("@/pages/security/PatrolHistory")),
    protection: "security",
    parentCode: "security_patrols",
    sortOrder: 3,
  },
  {
    path: "/security/team",
    menuCode: "security_team",
    title: { en: "Security Team", ar: "فريق الأمن" },
    icon: Users,
    component: lazyWithRetry(() => import("@/pages/security/SecurityTeam")),
    protection: "security",
    parentCode: "workforce_command",
    sortOrder: 1,
  },
  {
    path: "/security/command-center",
    menuCode: "command_center",
    title: { en: "Command Center", ar: "مركز القيادة" },
    icon: Radio,
    component: lazyWithRetry(() => import("@/pages/security/CommandCenter")),
    protection: "security",
    parentCode: "workforce_command",
    sortOrder: 2,
  },
  {
    path: "/security/zones",
    menuCode: "security_zones",
    title: { en: "Security Zones", ar: "مناطق الأمن" },
    icon: MapPin,
    component: lazyWithRetry(() => import("@/pages/security/SecurityZones")),
    protection: "security",
    parentCode: "workforce_command",
    sortOrder: 3,
  },
  {
    path: "/security/shifts",
    menuCode: "security_shifts",
    title: { en: "Shifts", ar: "المناوبات" },
    icon: Clock,
    component: lazyWithRetry(() => import("@/pages/security/SecurityShifts")),
    protection: "security",
    parentCode: "workforce_command",
    sortOrder: 4,
  },
  {
    path: "/security/roster",
    menuCode: "shift_roster",
    title: { en: "Shift Roster", ar: "جدول المناوبات" },
    icon: Calendar,
    component: lazyWithRetry(() => import("@/pages/security/ShiftRoster")),
    protection: "security",
    parentCode: "workforce_command",
    sortOrder: 5,
  },
  {
    path: "/security/my-location",
    menuCode: "my_location",
    title: { en: "My Location", ar: "موقعي" },
    icon: MapPin,
    component: lazyWithRetry(() => import("@/pages/security/GuardLocation")),
    protection: "security",
    parentCode: "workforce_command",
    sortOrder: 6,
  },
  {
    path: "/security/attendance",
    menuCode: "guard_attendance",
    title: { en: "Guard Attendance", ar: "حضور الحراس" },
    icon: Clock,
    component: lazyWithRetry(() => import("@/pages/security/GuardAttendance")),
    protection: "security",
    parentCode: "security_operations",
    sortOrder: 1,
  },
  {
    path: "/security/cctv",
    menuCode: "cctv_management",
    title: { en: "CCTV Management", ar: "إدارة كاميرات المراقبة" },
    icon: Video,
    component: lazyWithRetry(() => import("@/pages/security/CCTVManagement")),
    protection: "security",
    parentCode: "security_operations",
    sortOrder: 2,
  },
  {
    path: "/security/emergency-alerts",
    menuCode: "emergency_alerts",
    title: { en: "Emergency Alerts", ar: "تنبيهات الطوارئ" },
    icon: Bell,
    component: lazyWithRetry(() => import("@/pages/security/EmergencyAlerts")),
    protection: "security",
    parentCode: "security_operations",
    sortOrder: 3,
  },
  {
    path: "/security/handover",
    menuCode: "shift_handover",
    title: { en: "Shift Handover", ar: "تسليم المناوبة" },
    icon: FileText,
    component: lazyWithRetry(() => import("@/pages/security/ShiftHandover")),
    protection: "security",
    parentCode: "security_operations",
    sortOrder: 4,
  },
  {
    path: "/security/performance",
    menuCode: "guard_performance",
    title: { en: "Guard Performance", ar: "أداء الحراس" },
    icon: BarChart3,
    component: lazyWithRetry(() => import("@/pages/security/GuardPerformance")),
    protection: "security",
    parentCode: "security_operations",
    sortOrder: 5,
  },
  {
    path: "/security/guard-app",
    menuCode: "guard_mobile_app",
    title: { en: "Guard Mobile", ar: "تطبيق الحارس" },
    icon: MapPin,
    component: lazyWithRetry(() => import("@/pages/security/GuardMobileDashboard")),
    protection: "security",
    parentCode: "security_operations",
    sortOrder: 6,
  },
  {
    path: "/security/contractors",
    menuCode: "contractor_list",
    title: { en: "Legacy Contractors", ar: "المقاولين القديم" },
    icon: List,
    component: lazyWithRetry(() => import("@/pages/security/Contractors")),
    protection: "security",
    parentCode: "security",
    sortOrder: 20,
  },
  {
    path: "/security/gate",
    menuCode: "gate_control",
    title: { en: "Gate Control", ar: "التحكم بالبوابة" },
    icon: Shield,
    component: lazyWithRetry(() => import("@/pages/security/GateControl")),
    protection: "security",
    hidden: true,
    hiddenReason: "Legacy page - use gate-dashboard instead",
  },

  // -------------------------------------------------------------------------
  // ASSETS MODULE
  // -------------------------------------------------------------------------
  {
    path: "/assets/dashboard",
    menuCode: "asset_dashboard",
    title: { en: "Asset Dashboard", ar: "لوحة الأصول" },
    icon: BarChart3,
    component: lazyWithRetry(() => import("@/pages/assets/AssetDashboard")),
    protection: "protected",
    parentCode: "asset_management",
    sortOrder: 1,
  },
  {
    path: "/assets",
    menuCode: "asset_list",
    title: { en: "Asset List", ar: "قائمة الأصول" },
    icon: List,
    component: lazyWithRetry(() => import("@/pages/assets/AssetList")),
    protection: "protected",
    parentCode: "asset_management",
    sortOrder: 2,
  },
  {
    path: "/assets/register",
    menuCode: "register_asset",
    title: { en: "Register Asset", ar: "تسجيل أصل" },
    icon: Plus,
    component: lazyWithRetry(() => import("@/pages/assets/AssetRegister")),
    protection: "hsse",
    parentCode: "asset_management",
    sortOrder: 3,
  },
  {
    path: "/assets/scan",
    menuCode: "scan_asset",
    title: { en: "Scan Asset", ar: "مسح الأصل" },
    icon: QrCode,
    component: lazyWithRetry(() => import("@/pages/assets/AssetScanner")),
    protection: "protected",
    parentCode: "asset_management",
    sortOrder: 4,
  },
  {
    path: "/assets/mobile-scan",
    menuCode: "mobile_asset_scan",
    title: { en: "Mobile Scanner", ar: "الماسح المحمول" },
    icon: Smartphone,
    component: lazyWithRetry(() => import("@/pages/assets/MobileAssetScanner")),
    protection: "protected",
    hidden: true,
    hiddenReason: "Mobile-specific page",
  },
  {
    path: "/assets/bulk-print",
    menuCode: "bulk_print_labels",
    title: { en: "Bulk Print Labels", ar: "طباعة الملصقات" },
    icon: FileStack,
    component: lazyWithRetry(() => import("@/pages/assets/BulkPrintLabels")),
    protection: "hsse",
    hidden: true,
    hiddenReason: "Action page - accessed via asset list",
  },
  {
    path: "/assets/:id",
    menuCode: "asset_detail",
    title: { en: "Asset Detail", ar: "تفاصيل الأصل" },
    icon: Package,
    component: lazyWithRetry(() => import("@/pages/assets/AssetDetail")),
    protection: "protected",
    hidden: true,
    hiddenReason: "Dynamic route - accessed via asset list",
  },
  {
    path: "/assets/:id/edit",
    menuCode: "asset_edit",
    title: { en: "Edit Asset", ar: "تعديل الأصل" },
    icon: Settings2,
    component: lazyWithRetry(() => import("@/pages/assets/AssetRegister")),
    protection: "hsse",
    hidden: true,
    hiddenReason: "Dynamic route - accessed via asset detail",
  },
  {
    path: "/assets/:id/financials",
    menuCode: "asset_financials",
    title: { en: "Asset Financials", ar: "ماليات الأصل" },
    icon: DollarSign,
    component: lazyWithRetry(() => import("@/pages/assets/AssetFinancials")),
    protection: "protected",
    hidden: true,
    hiddenReason: "Dynamic route - accessed via asset detail",
  },
  {
    path: "/assets/:id/health",
    menuCode: "asset_health",
    title: { en: "Asset Health", ar: "صحة الأصل" },
    icon: HeartPulse,
    component: lazyWithRetry(() => import("@/pages/assets/AssetHealth")),
    protection: "protected",
    hidden: true,
    hiddenReason: "Dynamic route - accessed via asset detail",
  },
  {
    path: "/assets/:id/depreciation",
    menuCode: "asset_depreciation_detail",
    title: { en: "Asset Depreciation", ar: "إهلاك الأصل" },
    icon: Calculator,
    component: lazyWithRetry(() => import("@/pages/assets/AssetDepreciation")),
    protection: "protected",
    hidden: true,
    hiddenReason: "Dynamic route - accessed via asset detail",
  },
  {
    path: "/assets/:id/inspections/:inspectionId",
    menuCode: "asset_inspection_workspace",
    title: { en: "Asset Inspection", ar: "فحص الأصل" },
    icon: ClipboardCheck,
    component: lazyWithRetry(() => import("@/pages/assets/InspectionWorkspace")),
    protection: "hsse",
    hidden: true,
    hiddenReason: "Dynamic route - accessed via asset inspections",
  },
  {
    path: "/assets/purchase-requests",
    menuCode: "purchase_requests",
    title: { en: "Purchase Requests", ar: "طلبات الشراء" },
    icon: CreditCard,
    component: lazyWithRetry(() => import("@/pages/assets/PurchaseRequestsPage")),
    protection: "hsse",
    parentCode: "asset_management",
    sortOrder: 5,
  },
  {
    path: "/assets/approval-workflows",
    menuCode: "approval_workflows",
    title: { en: "Approval Workflows", ar: "سير عمل الموافقة" },
    icon: Workflow,
    component: lazyWithRetry(() => import("@/pages/assets/ApprovalWorkflowConfigPage")),
    protection: "admin",
    parentCode: "asset_management",
    sortOrder: 6,
  },
  {
    path: "/assets/warranties",
    menuCode: "asset_warranties",
    title: { en: "Asset Warranties", ar: "ضمانات الأصول" },
    icon: Shield,
    component: lazyWithRetry(() => import("@/pages/assets/AssetWarranties")),
    protection: "protected",
    hidden: true,
    hiddenReason: "Accessed via asset detail",
  },
  {
    path: "/assets/reports",
    menuCode: "asset_reports",
    title: { en: "Asset Reports", ar: "تقارير الأصول" },
    icon: FileStack,
    component: lazyWithRetry(() => import("@/pages/assets/AssetReports")),
    protection: "hsse",
    hidden: true,
    hiddenReason: "Accessed via dashboard",
  },
  {
    path: "/assets/reports/builder",
    menuCode: "asset_report_builder",
    title: { en: "Report Builder", ar: "منشئ التقارير" },
    icon: FileStack,
    component: lazyWithRetry(() => import("@/pages/assets/AssetReportBuilder")),
    protection: "hsse",
    hidden: true,
    hiddenReason: "Accessed via asset reports",
  },
  {
    path: "/assets/map",
    menuCode: "asset_map",
    title: { en: "Asset Map", ar: "خريطة الأصول" },
    icon: Map,
    component: lazyWithRetry(() => import("@/pages/assets/AssetMap")),
    protection: "protected",
    hidden: true,
    hiddenReason: "Accessed via dashboard",
  },
  {
    path: "/assets/audit-log",
    menuCode: "asset_audit_log",
    title: { en: "Asset Audit Log", ar: "سجل تدقيق الأصول" },
    icon: History,
    component: lazyWithRetry(() => import("@/pages/assets/AssetAuditLog")),
    protection: "hsse",
    parentCode: "asset_management",
    sortOrder: 8,
  },

  // Parts Inventory
  {
    path: "/parts/inventory",
    menuCode: "parts_inventory",
    title: { en: "Parts Inventory", ar: "مخزون القطع" },
    icon: Wrench,
    component: lazyWithRetry(() => import("@/pages/parts/PartsInventoryPage")),
    protection: "hsse",
    hidden: true,
    hiddenReason: "Accessed via asset module",
  },

  // -------------------------------------------------------------------------
  // CONTRACTORS MODULE
  // -------------------------------------------------------------------------
  {
    path: "/contractors",
    menuCode: "contractor_dashboard",
    title: { en: "Contractor Dashboard", ar: "لوحة المقاولين" },
    icon: LayoutDashboard,
    component: lazyWithRetry(() => import("@/pages/contractors/Dashboard")),
    protection: "admin",
    parentCode: "contractors_module",
    sortOrder: 1,
  },
  {
    path: "/contractors/companies",
    menuCode: "contractor_companies",
    title: { en: "Companies", ar: "الشركات" },
    icon: Building2,
    component: lazyWithRetry(() => import("@/pages/contractors/Companies")),
    protection: "admin",
    parentCode: "contractors_module",
    sortOrder: 2,
  },
  {
    path: "/contractors/projects",
    menuCode: "contractor_projects",
    title: { en: "Projects", ar: "المشاريع" },
    icon: Briefcase,
    component: lazyWithRetry(() => import("@/pages/contractors/Projects")),
    protection: "admin",
    parentCode: "contractors_module",
    sortOrder: 3,
  },
  {
    path: "/contractors/workers",
    menuCode: "contractor_workers",
    title: { en: "Workers", ar: "العمال" },
    icon: Users,
    component: lazyWithRetry(() => import("@/pages/contractors/Workers")),
    protection: "admin",
    parentCode: "contractors_module",
    sortOrder: 4,
  },
  {
    path: "/contractors/gate-passes",
    menuCode: "contractor_gate_passes",
    title: { en: "Gate Passes", ar: "تصاريح الدخول" },
    icon: FileWarning,
    component: lazyWithRetry(() => import("@/pages/contractors/GatePasses")),
    protection: "admin",
    parentCode: "contractors_module",
    sortOrder: 5,
  },
  {
    path: "/contractors/induction-videos",
    menuCode: "contractor_induction_videos",
    title: { en: "Induction Videos", ar: "فيديوهات التعريف" },
    icon: Video,
    component: lazyWithRetry(() => import("@/pages/contractors/InductionVideos")),
    protection: "admin",
    parentCode: "contractors_module",
    sortOrder: 6,
  },
  {
    path: "/contractors/analytics",
    menuCode: "contractor_analytics",
    title: { en: "Analytics", ar: "التحليلات" },
    icon: BarChart3,
    component: lazyWithRetry(() => import("@/pages/contractors/Analytics")),
    protection: "admin",
    parentCode: "contractors_module",
    sortOrder: 7,
  },
  {
    path: "/contractors/settings",
    menuCode: "contractor_settings",
    title: { en: "Contractor Settings", ar: "إعدادات المقاولين" },
    icon: Settings2,
    component: lazyWithRetry(() => import("@/pages/contractors/GatePassSettings")),
    protection: "admin",
    parentCode: "contractors_module",
    sortOrder: 8,
  },

  // Contractor Portal (for external contractor reps)
  {
    path: "/contractor-portal",
    menuCode: "contractor_portal_dashboard",
    title: { en: "Contractor Portal", ar: "بوابة المقاول" },
    icon: Building2,
    component: lazyWithRetry(() => import("@/pages/contractor-portal/Dashboard")),
    protection: "protected",
    hidden: true,
    hiddenReason: "External portal for contractor users only",
  },
  {
    path: "/contractor-portal/workers",
    menuCode: "contractor_portal_workers",
    title: { en: "Portal Workers", ar: "عمال البوابة" },
    icon: Users,
    component: lazyWithRetry(() => import("@/pages/contractor-portal/Workers")),
    protection: "protected",
    hidden: true,
    hiddenReason: "External portal for contractor users only",
  },
  {
    path: "/contractor-portal/projects",
    menuCode: "contractor_portal_projects",
    title: { en: "Portal Projects", ar: "مشاريع البوابة" },
    icon: Briefcase,
    component: lazyWithRetry(() => import("@/pages/contractor-portal/Projects")),
    protection: "protected",
    hidden: true,
    hiddenReason: "External portal for contractor users only",
  },
  {
    path: "/contractor-portal/gate-passes",
    menuCode: "contractor_portal_gate_passes",
    title: { en: "Portal Gate Passes", ar: "تصاريح البوابة" },
    icon: FileWarning,
    component: lazyWithRetry(() => import("@/pages/contractor-portal/GatePasses")),
    protection: "protected",
    hidden: true,
    hiddenReason: "External portal for contractor users only",
  },
  {
    path: "/contractor-portal/activity-log",
    menuCode: "contractor_portal_activity_log",
    title: { en: "Activity Log", ar: "سجل النشاط" },
    icon: History,
    component: lazyWithRetry(() => import("@/pages/contractor-portal/ActivityLog")),
    protection: "protected",
    hidden: true,
    hiddenReason: "External portal for contractor users only",
  },

  // Client Site Representative
  {
    path: "/client-site-rep",
    menuCode: "client_site_rep_dashboard",
    title: { en: "Site Representative Dashboard", ar: "لوحة ممثل الموقع" },
    icon: Building2,
    component: lazyWithRetry(() => import("@/pages/client-site-rep/Dashboard")),
    protection: "protected",
    parentCode: "contractors_module",
    sortOrder: 10,
  },

  // -------------------------------------------------------------------------
  // PTW (PERMIT TO WORK) MODULE
  // -------------------------------------------------------------------------
  {
    path: "/ptw",
    menuCode: "ptw_dashboard",
    title: { en: "PTW Dashboard", ar: "لوحة تصاريح العمل" },
    icon: LayoutDashboard,
    component: lazyWithRetry(() => import("@/pages/ptw/PTWDashboard")),
    protection: "hsse",
    parentCode: "ptw_module",
    sortOrder: 1,
  },
  {
    path: "/ptw/projects",
    menuCode: "ptw_projects",
    title: { en: "Project Mobilization", ar: "تعبئة المشروع" },
    icon: HardHat,
    component: lazyWithRetry(() => import("@/pages/ptw/ProjectMobilization")),
    protection: "hsse",
    parentCode: "ptw_module",
    sortOrder: 2,
  },
  {
    path: "/ptw/projects/:projectId/clearance",
    menuCode: "ptw_project_clearance",
    title: { en: "Project Clearance", ar: "تخليص المشروع" },
    icon: CheckCircle2,
    component: lazyWithRetry(() => import("@/pages/ptw/ProjectClearance")),
    protection: "hsse",
    hidden: true,
    hiddenReason: "Dynamic route - accessed via project list",
  },
  {
    path: "/ptw/console",
    menuCode: "ptw_console",
    title: { en: "Permit Console", ar: "وحدة التحكم بالتصاريح" },
    icon: Map,
    component: lazyWithRetry(() => import("@/pages/ptw/PermitConsole")),
    protection: "hsse",
    parentCode: "ptw_module",
    sortOrder: 3,
  },
  {
    path: "/ptw/create",
    menuCode: "ptw_create",
    title: { en: "Create Permit", ar: "إنشاء تصريح" },
    icon: Plus,
    component: lazyWithRetry(() => import("@/pages/ptw/CreatePermit")),
    protection: "hsse",
    parentCode: "ptw_module",
    sortOrder: 4,
  },
  {
    path: "/ptw/permits/:id",
    menuCode: "ptw_permit_view",
    title: { en: "Permit View", ar: "عرض التصريح" },
    icon: Eye,
    component: lazyWithRetry(() => import("@/pages/ptw/PermitView")),
    protection: "hsse",
    hidden: true,
    hiddenReason: "Dynamic route - accessed via permit console",
  },
  {
    path: "/ptw/inspection/:id",
    menuCode: "ptw_field_inspection",
    title: { en: "Field Inspection", ar: "فحص ميداني" },
    icon: ClipboardCheck,
    component: lazyWithRetry(() => import("@/pages/ptw/PTWFieldInspection")),
    protection: "hsse",
    hidden: true,
    hiddenReason: "Dynamic route - accessed via permit",
  },

  // Risk Assessments
  {
    path: "/risk-assessments",
    menuCode: "ptw_risk_assessments",
    title: { en: "Risk Assessments", ar: "تقييم المخاطر" },
    icon: AlertTriangle,
    component: lazyWithRetry(() => import("@/pages/RiskAssessments")),
    protection: "hsse",
    parentCode: "ptw_module",
    sortOrder: 5,
  },
  {
    path: "/risk-assessments/create",
    menuCode: "risk_assessment_create",
    title: { en: "Create Risk Assessment", ar: "إنشاء تقييم مخاطر" },
    icon: Plus,
    component: lazyWithRetry(() => import("@/pages/RiskAssessmentCreate")),
    protection: "hsse",
    hidden: true,
    hiddenReason: "Action page - accessed via risk assessments list",
  },

  // -------------------------------------------------------------------------
  // ADMIN ROUTES
  // -------------------------------------------------------------------------
  
  // SLA Management
  {
    path: "/admin/sla-dashboard",
    menuCode: "admin_sla_dashboard",
    title: { en: "SLA Dashboard", ar: "لوحة اتفاقية مستوى الخدمة" },
    icon: BarChart3,
    component: lazyWithRetry(() => import("@/pages/admin/SLADashboard")),
    protection: "hsse",
    parentCode: "admin_sla_management",
    sortOrder: 1,
  },
  {
    path: "/admin/action-sla",
    menuCode: "admin_action_sla",
    title: { en: "Action SLA Settings", ar: "إعدادات SLA الإجراءات" },
    icon: ClipboardList,
    component: lazyWithRetry(() => import("@/pages/admin/ActionSLASettings")),
    protection: "admin",
    parentCode: "admin_sla_management",
    sortOrder: 2,
  },
  {
    path: "/admin/finding-sla",
    menuCode: "admin_finding_sla",
    title: { en: "Finding SLA Settings", ar: "إعدادات SLA النتائج" },
    icon: ClipboardCheck,
    component: lazyWithRetry(() => import("@/pages/admin/FindingSLASettings")),
    protection: "admin",
    parentCode: "admin_sla_management",
    sortOrder: 3,
  },
  {
    path: "/admin/investigation-sla",
    menuCode: "admin_investigation_sla",
    title: { en: "Investigation SLA", ar: "SLA التحقيق" },
    icon: FileWarning,
    component: lazyWithRetry(() => import("@/pages/admin/InvestigationSLASettings")),
    protection: "admin",
    parentCode: "admin_sla_management",
    sortOrder: 4,
  },
  {
    path: "/admin/violation-sla",
    menuCode: "admin_violation_sla",
    title: { en: "Violation Settings", ar: "إعدادات المخالفات" },
    icon: AlertTriangle,
    component: lazyWithRetry(() => import("@/pages/admin/ViolationSettings")),
    protection: "admin",
    parentCode: "admin_sla_management",
    sortOrder: 5,
  },
  {
    path: "/admin/sla-analytics",
    menuCode: "admin_sla_analytics",
    title: { en: "SLA Analytics", ar: "تحليلات SLA" },
    icon: BarChart3,
    component: lazyWithRetry(() => import("@/pages/admin/SLAAnalytics")),
    protection: "admin",
    parentCode: "admin_sla_management",
    sortOrder: 6,
  },

  // User & Access
  {
    path: "/admin/users",
    menuCode: "admin_users",
    title: { en: "User Management", ar: "إدارة المستخدمين" },
    icon: Users,
    component: lazyWithRetry(() => import("@/pages/admin/UserManagement")),
    protection: "admin",
    parentCode: "admin_user_access",
    sortOrder: 1,
  },
  {
    path: "/admin/org-structure",
    menuCode: "admin_org",
    title: { en: "Org Structure", ar: "الهيكل التنظيمي" },
    icon: Network,
    component: lazyWithRetry(() => import("@/pages/admin/OrgStructure")),
    protection: "menu-based",
    menuBasedCode: "admin_org",
    parentCode: "admin_user_access",
    sortOrder: 2,
  },
  {
    path: "/admin/menu-access",
    menuCode: "admin_menu_access",
    title: { en: "Menu Access", ar: "الوصول للقوائم" },
    icon: Menu,
    component: lazyWithRetry(() => import("@/pages/admin/MenuAccessConfig")),
    protection: "admin",
    parentCode: "admin_user_access",
    sortOrder: 3,
  },
  {
    path: "/admin/user-menu-access",
    menuCode: "admin_user_menu_access",
    title: { en: "User Menu Access", ar: "وصول المستخدم للقوائم" },
    icon: UserCheck,
    component: lazyWithRetry(() => import("@/pages/admin/UserMenuAccessConfig")),
    protection: "admin",
    parentCode: "admin_user_access",
    sortOrder: 4,
  },
  {
    path: "/admin/security-audit",
    menuCode: "admin_security_audit",
    title: { en: "Security Audit", ar: "تدقيق الأمان" },
    icon: ShieldAlert,
    component: lazyWithRetry(() => import("@/pages/admin/SecurityAuditLog")),
    protection: "admin",
    parentCode: "admin_user_access",
    sortOrder: 5,
  },

  // Notifications
  {
    path: "/admin/hsse-notifications",
    menuCode: "admin_hsse_notifications",
    title: { en: "HSSE Notifications", ar: "إشعارات HSSE" },
    icon: ShieldAlert,
    component: lazyWithRetry(() => import("@/pages/admin/HSSENotifications")),
    protection: "admin",
    parentCode: "admin_notifications_group",
    sortOrder: 1,
  },
  {
    path: "/admin/hsse-notification-analytics",
    menuCode: "admin_hsse_notification_analytics",
    title: { en: "Notification Analytics", ar: "تحليلات الإشعارات" },
    icon: BarChart3,
    component: lazyWithRetry(() => import("@/pages/admin/HSSENotificationAnalytics")),
    protection: "admin",
    parentCode: "admin_notifications_group",
    sortOrder: 2,
  },
  {
    path: "/admin/whatsapp-settings",
    menuCode: "admin_whatsapp_settings",
    title: { en: "WhatsApp Settings", ar: "إعدادات واتساب" },
    icon: Settings2,
    component: lazyWithRetry(() => import("@/pages/admin/WhatsAppSettingsPage")),
    protection: "admin",
    parentCode: "admin_whatsapp",
    sortOrder: 1,
  },
  {
    path: "/admin/whatsapp-templates",
    menuCode: "admin_whatsapp_templates",
    title: { en: "Message Templates", ar: "قوالب الرسائل" },
    icon: FileText,
    component: lazyWithRetry(() => import("@/pages/admin/NotificationTemplates")),
    protection: "admin",
    parentCode: "admin_whatsapp",
    sortOrder: 2,
  },
  {
    path: "/admin/notification-logs",
    menuCode: "admin_notification_logs",
    title: { en: "Delivery Log", ar: "سجل التسليم" },
    icon: Radio,
    component: lazyWithRetry(() => import("@/pages/admin/NotificationDeliveryLog")),
    protection: "admin",
    parentCode: "admin_whatsapp",
    sortOrder: 3,
  },
  {
    path: "/admin/webpage-notifications",
    menuCode: "admin_webpage_notifications",
    title: { en: "Webpage Notifications", ar: "إشعارات الويب" },
    icon: Globe,
    component: lazyWithRetry(() => import("@/pages/admin/WebpageNotificationSettings")),
    protection: "admin",
    parentCode: "admin_notifications_group",
    sortOrder: 4,
  },
  {
    path: "/admin/page-content-editor",
    menuCode: "admin_page_content_editor",
    title: { en: "Page Content Editor", ar: "محرر محتوى الصفحة" },
    icon: Languages,
    component: lazyWithRetry(() => import("@/pages/admin/PageContentEditor")),
    protection: "admin",
    parentCode: "admin_notifications_group",
    sortOrder: 5,
  },
  {
    path: "/admin/test-push",
    menuCode: "admin_test_push",
    title: { en: "Test Push Notifications", ar: "اختبار الإشعارات" },
    icon: Bell,
    component: lazyWithRetry(() => import("@/pages/admin/TestPushNotifications")),
    protection: "admin",
    parentCode: "admin_notifications_group",
    sortOrder: 6,
  },

  // Reporting & KPIs
  {
    path: "/admin/team-performance",
    menuCode: "admin_team_performance",
    title: { en: "Team Performance", ar: "أداء الفريق" },
    icon: Users,
    component: lazyWithRetry(() => import("@/pages/admin/TeamPerformance")),
    protection: "hsse",
    parentCode: "admin_reporting_kpis",
    sortOrder: 1,
  },
  {
    path: "/admin/executive-report",
    menuCode: "admin_executive_report",
    title: { en: "Executive Report", ar: "التقرير التنفيذي" },
    icon: FileStack,
    component: lazyWithRetry(() => import("@/pages/admin/ExecutiveReport")),
    protection: "hsse",
    parentCode: "admin_reporting_kpis",
    sortOrder: 2,
  },
  {
    path: "/admin/kpi-targets",
    menuCode: "admin_kpi_targets",
    title: { en: "KPI Targets", ar: "أهداف مؤشرات الأداء" },
    icon: BarChart3,
    component: lazyWithRetry(() => import("@/pages/admin/KPITargetsManagement")),
    protection: "admin",
    parentCode: "admin_reporting_kpis",
    sortOrder: 3,
  },
  {
    path: "/admin/kpi-targets/audit",
    menuCode: "admin_kpi_audit",
    title: { en: "KPI Audit Log", ar: "سجل تدقيق KPI" },
    icon: History,
    component: lazyWithRetry(() => import("@/pages/admin/KPIAuditLogPage")),
    protection: "admin",
    hidden: true,
    hiddenReason: "Accessed via KPI targets page",
  },
  {
    path: "/admin/analytics",
    menuCode: "admin_analytics",
    title: { en: "Usage Analytics", ar: "تحليلات الاستخدام" },
    icon: BarChart3,
    component: lazyWithRetry(() => import("@/pages/admin/UsageAnalytics")),
    protection: "admin",
    parentCode: "admin_reporting_kpis",
    sortOrder: 4,
  },

  // System Configuration
  {
    path: "/admin/branding",
    menuCode: "admin_branding",
    title: { en: "Brand Management", ar: "إدارة العلامة التجارية" },
    icon: Building2,
    component: lazyWithRetry(() => import("@/pages/AdminBranding")),
    protection: "admin",
    parentCode: "admin_system_config",
    sortOrder: 1,
  },
  {
    path: "/admin/document-settings",
    menuCode: "admin_document_settings",
    title: { en: "Document Settings", ar: "إعدادات المستندات" },
    icon: FileCog,
    component: lazyWithRetry(() => import("@/pages/admin/DocumentSettings")),
    protection: "admin",
    parentCode: "admin_system_config",
    sortOrder: 2,
  },
  {
    path: "/admin/event-categories",
    menuCode: "settings_event_categories",
    title: { en: "Event Categories", ar: "فئات الأحداث" },
    icon: List,
    component: lazyWithRetry(() => import("@/pages/admin/EventCategorySettings")),
    protection: "admin",
    parentCode: "admin_system_config",
    sortOrder: 3,
  },
  {
    path: "/admin/workflow-diagrams",
    menuCode: "admin_workflow_diagrams",
    title: { en: "Workflow Diagrams", ar: "مخططات سير العمل" },
    icon: Workflow,
    component: lazyWithRetry(() => import("@/pages/admin/WorkflowDiagrams")),
    protection: "admin",
    parentCode: "admin_system_config",
    sortOrder: 4,
  },
  {
    path: "/admin/manhours",
    menuCode: "admin_manhours",
    title: { en: "Manhours Management", ar: "إدارة ساعات العمل" },
    icon: Clock,
    component: lazyWithRetry(() => import("@/pages/admin/ManhoursManagement")),
    protection: "admin",
    parentCode: "admin_system_config",
    sortOrder: 5,
  },
  {
    path: "/admin/platform-settings",
    menuCode: "admin_platform_settings",
    title: { en: "Platform Settings", ar: "إعدادات المنصة" },
    icon: Settings2,
    component: lazyWithRetry(() => import("@/pages/admin/PlatformSettings")),
    protection: "admin",
    parentCode: "admin_system_config",
    sortOrder: 6,
  },
  {
    path: "/admin/emergency-instructions",
    menuCode: "admin_emergency_instructions",
    title: { en: "Emergency Instructions", ar: "تعليمات الطوارئ" },
    icon: AlertTriangle,
    component: lazyWithRetry(() => import("@/pages/admin/EmergencyInstructionsSettings")),
    protection: "admin",
    parentCode: "admin_system_config",
    sortOrder: 7,
  },
  {
    path: "/admin/visitor-settings",
    menuCode: "admin_visitor_settings",
    title: { en: "Visitor Settings", ar: "إعدادات الزوار" },
    icon: Users,
    component: lazyWithRetry(() => import("@/pages/admin/VisitorSettings")),
    protection: "admin",
    parentCode: "admin_system_config",
    sortOrder: 8,
  },
  {
    path: "/admin/pending-approvals-override",
    menuCode: "admin_pending_approvals_override",
    title: { en: "Pending Approvals Override", ar: "تجاوز الموافقات المعلقة" },
    icon: ShieldCheck,
    component: lazyWithRetry(() => import("@/pages/admin/PendingApprovalsOverride")),
    protection: "admin",
    parentCode: "admin_system_config",
    sortOrder: 9,
  },
  {
    path: "/admin/ai-settings",
    menuCode: "admin_ai_settings",
    title: { en: "AI Settings", ar: "إعدادات الذكاء الاصطناعي" },
    icon: Sparkles,
    component: lazyWithRetry(() => import("@/pages/admin/AISettings")),
    protection: "admin",
    parentCode: "admin_system_config",
    sortOrder: 10,
  },

  // Inspection & Asset Config
  {
    path: "/admin/inspection-templates",
    menuCode: "admin_templates",
    title: { en: "Inspection Templates", ar: "قوالب التفتيش" },
    icon: ClipboardList,
    component: lazyWithRetry(() => import("@/pages/admin/InspectionTemplates")),
    protection: "admin",
    parentCode: "audits_inspections",
    sortOrder: 10,
  },
  {
    path: "/admin/inspection-category-settings",
    menuCode: "admin_inspection_categories",
    title: { en: "Inspection Categories", ar: "فئات التفتيش" },
    icon: FolderTree,
    component: lazyWithRetry(() => import("@/pages/admin/InspectionCategorySettings")),
    protection: "admin",
    parentCode: "audits_inspections",
    sortOrder: 11,
  },
  {
    path: "/admin/asset-categories",
    menuCode: "admin_asset_categories",
    title: { en: "Asset Categories", ar: "فئات الأصول" },
    icon: FolderTree,
    component: lazyWithRetry(() => import("@/pages/admin/AssetCategorySettings")),
    protection: "admin",
    parentCode: "asset_management",
    sortOrder: 7,
  },
  {
    path: "/admin/hsse-validation",
    menuCode: "admin_hsse_validation",
    title: { en: "HSSE Validation", ar: "التحقق من HSSE" },
    icon: ShieldCheck,
    component: lazyWithRetry(() => import("@/pages/admin/HSSEValidationDashboard")),
    protection: "hsse",
    hidden: true,
    hiddenReason: "Internal validation tool",
  },

  // Platform Management (Super Admin)
  {
    path: "/admin/tenants",
    menuCode: "admin_tenants",
    title: { en: "Tenant Management", ar: "إدارة المستأجرين" },
    icon: Layers,
    component: lazyWithRetry(() => import("@/pages/admin/TenantManagement")),
    protection: "admin",
    parentCode: "admin_platform_management",
    sortOrder: 1,
  },
  {
    path: "/admin/subscriptions",
    menuCode: "admin_subscriptions",
    title: { en: "Subscriptions Overview", ar: "نظرة عامة على الاشتراكات" },
    icon: Receipt,
    component: lazyWithRetry(() => import("@/pages/admin/SubscriptionOverview")),
    protection: "admin",
    parentCode: "admin_platform_management",
    sortOrder: 2,
  },
  {
    path: "/admin/modules",
    menuCode: "admin_modules",
    title: { en: "Module Management", ar: "إدارة الوحدات" },
    icon: Puzzle,
    component: lazyWithRetry(() => import("@/pages/admin/ModuleManagement")),
    protection: "admin",
    parentCode: "admin_platform_management",
    sortOrder: 3,
  },
  {
    path: "/admin/plans",
    menuCode: "admin_plans",
    title: { en: "Plan Management", ar: "إدارة الخطط" },
    icon: FileStack,
    component: lazyWithRetry(() => import("@/pages/admin/PlanManagement")),
    protection: "admin",
    parentCode: "admin_platform_management",
    sortOrder: 4,
  },
  {
    path: "/admin/billing",
    menuCode: "admin_billing",
    title: { en: "Billing Overview", ar: "نظرة عامة على الفواتير" },
    icon: Receipt,
    component: lazyWithRetry(() => import("@/pages/admin/BillingOverview")),
    protection: "admin",
    parentCode: "admin_platform_management",
    sortOrder: 5,
  },
  {
    path: "/admin/support",
    menuCode: "admin_support",
    title: { en: "Support Dashboard", ar: "لوحة الدعم" },
    icon: HelpCircle,
    component: lazyWithRetry(() => import("@/pages/admin/SupportDashboard")),
    protection: "admin",
    parentCode: "admin_platform_management",
    sortOrder: 6,
  },
  {
    path: "/admin/app-updates",
    menuCode: "admin_app_updates",
    title: { en: "App Updates", ar: "تحديثات التطبيق" },
    icon: Bell,
    component: lazyWithRetry(() => import("@/pages/admin/AppUpdates")),
    protection: "admin",
    parentCode: "admin_platform_management",
    sortOrder: 7,
  },
  {
    path: "/admin/security-dashboard",
    menuCode: "admin_security_dashboard",
    title: { en: "Admin Security Dashboard", ar: "لوحة الأمان للمشرف" },
    icon: ShieldAlert,
    component: lazyWithRetry(() => import("@/pages/admin/SecurityDashboard")),
    protection: "admin",
    hidden: true,
    hiddenReason: "Accessed via security audit",
  },

  // Training
  {
    path: "/admin/training-center",
    menuCode: "training_center",
    title: { en: "Training Center", ar: "مركز التدريب" },
    icon: BookOpen,
    component: lazyWithRetry(() => import("@/pages/admin/TrainingCenter")),
    protection: "protected",
    parentCode: "training",
    sortOrder: 1,
  },

  // -------------------------------------------------------------------------
  // USER SETTINGS
  // -------------------------------------------------------------------------
  {
    path: "/support",
    menuCode: "support",
    title: { en: "Support", ar: "الدعم" },
    icon: LifeBuoy,
    component: lazyWithRetry(() => import("@/pages/Support")),
    protection: "protected",
    sortOrder: 100,
  },
  {
    path: "/settings/subscription",
    menuCode: "settings_subscription",
    title: { en: "Subscription", ar: "الاشتراك" },
    icon: CreditCard,
    component: lazyWithRetry(() => import("@/pages/admin/SubscriptionManagement")),
    protection: "protected",
    parentCode: "settings",
    sortOrder: 1,
  },
  {
    path: "/settings/usage-billing",
    menuCode: "settings_billing",
    title: { en: "Usage & Billing", ar: "الاستخدام والفواتير" },
    icon: Receipt,
    component: lazyWithRetry(() => import("@/pages/settings/UsageBilling")),
    protection: "protected",
    parentCode: "settings",
    sortOrder: 2,
  },
];

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

/**
 * Get a route by its path
 */
export function getRouteByPath(path: string): RouteDefinition | undefined {
  return routeRegistry.find(r => r.path === path);
}

/**
 * Get a route by its menu code
 */
export function getRouteByMenuCode(menuCode: string): RouteDefinition | undefined {
  return routeRegistry.find(r => r.menuCode === menuCode);
}

/**
 * Get all routes that should appear in sidebar (not hidden)
 */
export function getVisibleRoutes(): RouteDefinition[] {
  return routeRegistry.filter(r => !r.hidden);
}

/**
 * Get child routes for a parent menu code
 */
export function getChildRoutes(parentCode: string): RouteDefinition[] {
  return routeRegistry
    .filter(r => r.parentCode === parentCode && !r.hidden)
    .sort((a, b) => (a.sortOrder ?? 999) - (b.sortOrder ?? 999));
}

/**
 * Validate the registry for issues
 */
export function validateRegistry(): { valid: boolean; errors: string[] } {
  const errors: string[] = [];
  const paths = new Set<string>();
  const menuCodes = new Set<string>();

  for (const route of routeRegistry) {
    // Check for duplicate paths
    if (paths.has(route.path)) {
      errors.push(`Duplicate path: ${route.path}`);
    }
    paths.add(route.path);

    // Check for duplicate menu codes
    if (menuCodes.has(route.menuCode)) {
      errors.push(`Duplicate menuCode: ${route.menuCode}`);
    }
    menuCodes.add(route.menuCode);

    // Check hidden routes have reasons
    if (route.hidden && !route.hiddenReason) {
      errors.push(`Hidden route missing hiddenReason: ${route.path}`);
    }
  }

  return { valid: errors.length === 0, errors };
}
