// Re-export for backward compatibility
export { ProtectedRoute } from './auth/ProtectedRoute';
export { AdminRoute } from './auth/AdminRoute';
export { HSSERoute } from './auth/HSSERoute';
export { SecurityRoute } from './auth/SecurityRoute';
export { MenuBasedAdminRoute } from './auth/MenuBasedAdminRoute';
export { ModuleGate } from './auth/ModuleGate';
export { ErrorBoundary, withErrorBoundary } from './shared/ErrorBoundary';
export { PlaceholderPage } from './shared/PlaceholderPage';
export { RTLWrapper } from './layout/RTLWrapper';
export { NavLink } from './layout/NavLink';
export { SplashScreen } from './layout/SplashScreen';
export { SplashWrapper } from './layout/SplashWrapper';
export { default as AppSidebar } from './layout/AppSidebar';
export { SessionTimeoutWarning } from './session/SessionTimeoutWarning';
export { SessionManagementProvider } from './session/SessionManagementProvider';
export { SessionErrorBoundary } from './session/SessionErrorBoundary';
export { SessionFallbackUI } from './session/SessionFallbackUI';
export { NetworkStatusIndicator } from './pwa/NetworkStatusIndicator';
export { OnlineRetryHandler } from './pwa/OnlineRetryHandler';
export { ServiceWorkerUpdateNotifier } from './pwa/ServiceWorkerUpdateNotifier';
export { AppVersionIndicator } from './pwa/AppVersionIndicator';
export { WhatsNewDialog } from './pwa/WhatsNewDialog';
export { NotificationPermissionPrompt } from './notifications/NotificationPermissionPrompt';
export { NotificationPopover } from './notifications/NotificationPopover';
export { LanguageSelector } from './settings/LanguageSelector';
export { ThemeToggle } from './settings/ThemeToggle';
export { SubscriptionAuditLog } from './subscription/SubscriptionAuditLog';
export { PlanComparisonModal } from './subscription/PlanComparisonModal';
export { TrialBanner } from './subscription/TrialBanner';
export { UserLimitIndicator } from './subscription/UserLimitIndicator';
export { PageLoadErrorBoundary } from './shared/PageLoadErrorBoundary';
