import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

interface PushPayload {
  title: string;
  body: string;
  icon?: string;
  badge?: string;
  tag?: string;
  data?: Record<string, unknown>;
  actions?: Array<{ action: string; title: string }>;
  requireInteraction?: boolean;
}

type NotificationType = 
  | 'incidents_new'
  | 'incidents_assigned'
  | 'incidents_status_change'
  | 'approvals_requested'
  | 'approvals_decision'
  | 'sla_warnings'
  | 'sla_overdue'
  | 'sla_escalations'
  | 'system_announcements';

interface RequestBody {
  user_ids?: string[];
  tenant_id?: string;
  payload: PushPayload;
  notification_type?: NotificationType;
  language?: string;
}

interface PushSubscription {
  id: string;
  user_id: string;
  endpoint: string;
  p256dh_key: string;
  auth_key: string;
}

// Base64 URL encoding/decoding utilities
function base64UrlEncode(data: Uint8Array): string {
  const base64 = btoa(String.fromCharCode(...data));
  return base64.replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}

function base64UrlDecode(str: string): Uint8Array {
  // Clean the string first - remove any whitespace or newlines
  const cleanStr = str.replace(/\s+/g, '').replace(/[\r\n]/g, '');
  
  // Add padding if needed
  const padding = '='.repeat((4 - (cleanStr.length % 4)) % 4);
  const base64 = (cleanStr + padding).replace(/-/g, '+').replace(/_/g, '/');
  
  try {
    const rawData = atob(base64);
    return new Uint8Array([...rawData].map(char => char.charCodeAt(0)));
  } catch (error) {
    console.error('base64UrlDecode error for input length:', str.length, 'cleaned length:', cleanStr.length, 'first 20 chars:', cleanStr.substring(0, 20));
    throw error;
  }
}

// Safely decode base64url, handling both standard and URL-safe variants
function safeBase64UrlDecode(str: string): Uint8Array {
  // Clean the string - remove any whitespace, newlines, or invalid chars
  let cleanStr = str.replace(/[\s\r\n]/g, '');
  
  // Handle potential hex encoding (fallback)
  if (/^[0-9a-fA-F]+$/.test(cleanStr) && cleanStr.length === 64) {
    console.log('Detected hex-encoded key, converting...');
    const bytes = new Uint8Array(32);
    for (let i = 0; i < 32; i++) {
      bytes[i] = parseInt(cleanStr.substring(i * 2, i * 2 + 2), 16);
    }
    return bytes;
  }
  
  // Standard base64url decode with proper padding
  const padding = '='.repeat((4 - (cleanStr.length % 4)) % 4);
  const base64 = (cleanStr + padding).replace(/-/g, '+').replace(/_/g, '/');
  
  try {
    const rawData = atob(base64);
    return new Uint8Array([...rawData].map(char => char.charCodeAt(0)));
  } catch (error) {
    console.error('safeBase64UrlDecode failed, trying alternative decode...');
    // Try without the last character (sometimes there's a trailing issue)
    try {
      const trimmed = cleanStr.slice(0, -1);
      const trimPadding = '='.repeat((4 - (trimmed.length % 4)) % 4);
      const trimBase64 = (trimmed + trimPadding).replace(/-/g, '+').replace(/_/g, '/');
      const rawData = atob(trimBase64);
      return new Uint8Array([...rawData].map(char => char.charCodeAt(0)));
    } catch {
      throw error;
    }
  }
}

// Create JWT for VAPID authentication
async function createVapidJwt(
  audience: string,
  subject: string,
  privateKeyBase64: string
): Promise<string> {
  const header = { alg: 'ES256', typ: 'JWT' };
  const now = Math.floor(Date.now() / 1000);
  const payload = {
    aud: audience,
    exp: now + 12 * 60 * 60, // 12 hours
    sub: subject,
  };

  const headerB64 = base64UrlEncode(new TextEncoder().encode(JSON.stringify(header)));
  const payloadB64 = base64UrlEncode(new TextEncoder().encode(JSON.stringify(payload)));
  const unsignedToken = `${headerB64}.${payloadB64}`;

  // Import the private key using safe decoder
  console.log('VAPID private key input length:', privateKeyBase64.length);
  const privateKeyBytes = safeBase64UrlDecode(privateKeyBase64);
  
  console.log('Private key bytes length:', privateKeyBytes.length);
  
  let privateKey: CryptoKey;
  
  try {
    // First try as PKCS8 format (generated by Web Crypto exportKey)
    if (privateKeyBytes.length > 32) {
      privateKey = await crypto.subtle.importKey(
        'pkcs8',
        privateKeyBytes.buffer as ArrayBuffer,
        { name: 'ECDSA', namedCurve: 'P-256' },
        false,
        ['sign']
      );
    } else {
      // Try as raw 32-byte key
      const keyData = privateKeyBytes.length === 32 
        ? privateKeyBytes 
        : privateKeyBytes.slice(-32);

      privateKey = await crypto.subtle.importKey(
        'raw',
        keyData.buffer as ArrayBuffer,
        { name: 'ECDSA', namedCurve: 'P-256' },
        false,
        ['sign']
      );
    }
  } catch (importError) {
    console.error('Failed to import private key:', importError);
    throw new Error(`Failed to import VAPID private key: ${importError instanceof Error ? importError.message : 'Unknown error'}`);
  }

  // Sign the token
  const signature = await crypto.subtle.sign(
    { name: 'ECDSA', hash: 'SHA-256' },
    privateKey,
    new TextEncoder().encode(unsignedToken)
  );

  const signatureB64 = base64UrlEncode(new Uint8Array(signature));
  
  return `${unsignedToken}.${signatureB64}`;
}

// Generate encryption keys for push message
async function encryptPayload(
  payload: string,
  p256dhKey: string,
  authKey: string
): Promise<{ encrypted: Uint8Array; salt: Uint8Array; localPublicKey: Uint8Array }> {
  // Generate local key pair for ECDH
  const localKeyPair = await crypto.subtle.generateKey(
    { name: 'ECDH', namedCurve: 'P-256' },
    true,
    ['deriveBits']
  );

  // Import the subscriber's public key
  const subscriberKeyBytes = base64UrlDecode(p256dhKey);
  const subscriberPublicKey = await crypto.subtle.importKey(
    'raw',
    subscriberKeyBytes.buffer as ArrayBuffer,
    { name: 'ECDH', namedCurve: 'P-256' },
    false,
    []
  );

  // Derive shared secret
  const sharedSecret = await crypto.subtle.deriveBits(
    { name: 'ECDH', public: subscriberPublicKey },
    localKeyPair.privateKey,
    256
  );

  // Export local public key
  const localPublicKeyRaw = await crypto.subtle.exportKey('raw', localKeyPair.publicKey);
  const localPublicKey = new Uint8Array(localPublicKeyRaw);

  // Generate salt
  const salt = crypto.getRandomValues(new Uint8Array(16));

  // Decode auth secret
  const authSecret = base64UrlDecode(authKey);

  // HKDF for key derivation
  const sharedSecretKey = await crypto.subtle.importKey(
    'raw',
    sharedSecret,
    { name: 'HKDF' },
    false,
    ['deriveBits']
  );

  // PRK = HKDF-Extract(auth_secret, ecdh_secret)
  const authInfo = new TextEncoder().encode('Content-Encoding: auth\0');
  const prk = await crypto.subtle.deriveBits(
    {
      name: 'HKDF',
      hash: 'SHA-256',
      salt: authSecret.buffer as ArrayBuffer,
      info: authInfo,
    },
    sharedSecretKey,
    256
  );

  const prkKey = await crypto.subtle.importKey(
    'raw',
    prk,
    { name: 'HKDF' },
    false,
    ['deriveBits']
  );

  // Derive content encryption key
  const cekInfo = new TextEncoder().encode('Content-Encoding: aes128gcm\0');
  
  const cekBits = await crypto.subtle.deriveBits(
    {
      name: 'HKDF',
      hash: 'SHA-256',
      salt: salt.buffer as ArrayBuffer,
      info: cekInfo,
    },
    prkKey,
    128
  );

  // Derive nonce
  const nonceInfo = new TextEncoder().encode('Content-Encoding: nonce\0');
  const nonceBits = await crypto.subtle.deriveBits(
    {
      name: 'HKDF',
      hash: 'SHA-256',
      salt: salt.buffer as ArrayBuffer,
      info: nonceInfo,
    },
    prkKey,
    96
  );

  // Import AES key
  const aesKey = await crypto.subtle.importKey(
    'raw',
    cekBits,
    { name: 'AES-GCM' },
    false,
    ['encrypt']
  );

  // Pad the payload (add 2 bytes of padding length prefix)
  const payloadBytes = new TextEncoder().encode(payload);
  const paddedPayload = new Uint8Array(payloadBytes.length + 2);
  paddedPayload[0] = 0;
  paddedPayload[1] = 0;
  paddedPayload.set(payloadBytes, 2);

  // Encrypt
  const encrypted = await crypto.subtle.encrypt(
    { name: 'AES-GCM', iv: new Uint8Array(nonceBits) },
    aesKey,
    paddedPayload
  );

  return {
    encrypted: new Uint8Array(encrypted),
    salt,
    localPublicKey,
  };
}

// Build the encrypted content body
function buildEncryptedBody(
  encrypted: Uint8Array,
  salt: Uint8Array,
  localPublicKey: Uint8Array,
  recordSize: number = 4096
): Uint8Array {
  // Header: salt (16) + record size (4) + key length (1) + key (65)
  const header = new Uint8Array(86);
  header.set(salt, 0);
  
  // Record size (big-endian 4 bytes)
  const view = new DataView(header.buffer);
  view.setUint32(16, recordSize, false);
  
  // Key length
  header[20] = localPublicKey.length;
  
  // Key
  header.set(localPublicKey, 21);

  // Combine header and encrypted data
  const body = new Uint8Array(header.length + encrypted.length);
  body.set(header, 0);
  body.set(encrypted, header.length);

  return body;
}

// Send push notification to a single subscription
async function sendPushToSubscription(
  subscription: PushSubscription,
  payload: string,
  vapidPublicKey: string,
  vapidPrivateKey: string,
  vapidSubject: string
): Promise<{ success: boolean; statusCode?: number; error?: string }> {
  try {
    const endpoint = subscription.endpoint;
    const url = new URL(endpoint);
    const audience = `${url.protocol}//${url.host}`;

    // Create VAPID JWT
    const jwt = await createVapidJwt(audience, vapidSubject, vapidPrivateKey);

    // Encrypt the payload
    const { encrypted, salt, localPublicKey } = await encryptPayload(
      payload,
      subscription.p256dh_key,
      subscription.auth_key
    );

    // Build the body
    const body = buildEncryptedBody(encrypted, salt, localPublicKey);

    // Prepare headers
    const headers = {
      'Authorization': `vapid t=${jwt}, k=${vapidPublicKey}`,
      'Content-Encoding': 'aes128gcm',
      'Content-Type': 'application/octet-stream',
      'Content-Length': body.length.toString(),
      'TTL': '86400',
      'Urgency': 'high',
    };

    console.log(`Sending push to endpoint: ${endpoint.substring(0, 50)}...`);

    const response = await fetch(endpoint, {
      method: 'POST',
      headers,
      body: body.buffer as ArrayBuffer,
    });

    if (response.status === 201) {
      console.log(`Push sent successfully to subscription ${subscription.id}`);
      return { success: true, statusCode: response.status };
    } else if (response.status === 410 || response.status === 404) {
      console.log(`Subscription ${subscription.id} is no longer valid (${response.status})`);
      return { success: false, statusCode: response.status, error: 'Subscription expired' };
    } else {
      const errorText = await response.text();
      console.error(`Push failed with status ${response.status}: ${errorText}`);
      return { success: false, statusCode: response.status, error: errorText };
    }
  } catch (error) {
    console.error(`Error sending push to ${subscription.id}:`, error);
    return { 
      success: false, 
      error: error instanceof Error ? error.message : 'Unknown error' 
    };
  }
}

serve(async (req) => {
  // Handle CORS preflight
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const vapidPublicKey = Deno.env.get('VAPID_PUBLIC_KEY');
    const vapidPrivateKey = Deno.env.get('VAPID_PRIVATE_KEY');

    if (!vapidPublicKey || !vapidPrivateKey) {
      console.error('VAPID keys not configured');
      return new Response(
        JSON.stringify({ error: 'Push notifications not configured - VAPID keys missing' }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const supabase = createClient(supabaseUrl, supabaseServiceKey);
    const { user_ids, tenant_id, payload, notification_type }: RequestBody = await req.json();

    if (!payload || !payload.title || !payload.body) {
      return new Response(
        JSON.stringify({ error: 'Missing required payload fields (title, body)' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Build query for subscriptions
    let query = supabase
      .from('push_subscriptions')
      .select('id, user_id, endpoint, p256dh_key, auth_key')
      .eq('is_active', true)
      .is('deleted_at', null);

    if (user_ids && user_ids.length > 0) {
      query = query.in('user_id', user_ids);
    } else if (tenant_id) {
      query = query.eq('tenant_id', tenant_id);
    } else {
      return new Response(
        JSON.stringify({ error: 'Must specify user_ids or tenant_id' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Filter expired subscriptions
    query = query.or('expires_at.is.null,expires_at.gt.now()');

    const { data: subscriptions, error: fetchError } = await query;

    if (fetchError) {
      console.error('Error fetching subscriptions:', fetchError);
      return new Response(
        JSON.stringify({ error: 'Failed to fetch subscriptions' }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Filter by notification preferences if notification_type is specified
    let filteredSubscriptions = subscriptions || [];
    if (notification_type && filteredSubscriptions.length > 0) {
      const userIds = filteredSubscriptions.map(s => s.user_id);
      
      const { data: preferences, error: prefsError } = await supabase
        .from('push_notification_preferences')
        .select('user_id, incidents_new, incidents_assigned, incidents_status_change, approvals_requested, approvals_decision, sla_warnings, sla_overdue, sla_escalations, system_announcements')
        .in('user_id', userIds);

      if (!prefsError && preferences) {
        const usersWithPrefsDisabled = (preferences as Array<Record<string, unknown>>)
          .filter(p => p[notification_type] === false)
          .map(p => p.user_id as string);
        
        filteredSubscriptions = filteredSubscriptions.filter(
          s => !usersWithPrefsDisabled.includes(s.user_id)
        );
        
        console.log(`Filtered ${subscriptions?.length || 0} subscriptions to ${filteredSubscriptions.length} based on ${notification_type} preferences`);
      }
    }

    if (filteredSubscriptions.length === 0) {
      console.log('No active subscriptions found after filtering');
      return new Response(
        JSON.stringify({ sent: 0, failed: 0, message: 'No active subscriptions' }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    console.log(`Found ${filteredSubscriptions.length} active subscriptions after preference filtering`);

    // Prepare notification payload
    const notificationPayload = JSON.stringify({
      title: payload.title,
      body: payload.body,
      icon: payload.icon || 'https://xdlowvfzhvjzbtgvurzj.supabase.co/storage/v1/object/public/branding/9290e913-c735-405c-91c6-141e966011ae/favicon/1764707368310.png',
      badge: payload.badge || 'https://xdlowvfzhvjzbtgvurzj.supabase.co/storage/v1/object/public/branding/9290e913-c735-405c-91c6-141e966011ae/favicon/1764707368310.png',
      tag: payload.tag,
      data: payload.data,
      actions: payload.actions,
      requireInteraction: payload.requireInteraction || false,
    });

    // VAPID subject (must be mailto: or https:)
    const vapidSubject = 'mailto:support@lovable.dev';

    let sent = 0;
    let failed = 0;
    const expiredSubscriptionIds: string[] = [];

    // Send to each subscription
    for (const subscription of filteredSubscriptions) {
      const result = await sendPushToSubscription(
        subscription as PushSubscription,
        notificationPayload,
        vapidPublicKey,
        vapidPrivateKey,
        vapidSubject
      );

      if (result.success) {
        sent++;
      } else {
        failed++;
        if (result.statusCode === 410 || result.statusCode === 404) {
          expiredSubscriptionIds.push(subscription.id);
        }
      }
    }

    // Deactivate expired subscriptions
    if (expiredSubscriptionIds.length > 0) {
      const { error: updateError } = await supabase
        .from('push_subscriptions')
        .update({ is_active: false })
        .in('id', expiredSubscriptionIds);

      if (updateError) {
        console.error('Error deactivating expired subscriptions:', updateError);
      } else {
        console.log(`Deactivated ${expiredSubscriptionIds.length} expired subscriptions`);
      }
    }

    // Clean up old expired subscriptions
    const { error: cleanupError } = await supabase
      .from('push_subscriptions')
      .update({ is_active: false })
      .lt('expires_at', new Date().toISOString())
      .eq('is_active', true);

    if (cleanupError) {
      console.error('Error cleaning up expired subscriptions:', cleanupError);
    }

    console.log(`Push notification results: ${sent} sent, ${failed} failed`);

    return new Response(
      JSON.stringify({
        sent,
        failed,
        total: filteredSubscriptions.length,
        filtered_by_preferences: notification_type ? (subscriptions?.length || 0) - filteredSubscriptions.length : 0,
        message: `Successfully sent ${sent} notifications, ${failed} failed`,
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  } catch (error: unknown) {
    console.error('Error in send-push-notification:', error);
    const errorMessage = error instanceof Error ? error.message : 'Internal server error';
    return new Response(
      JSON.stringify({ error: errorMessage }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});
