/// <reference lib="webworker" />

// ============================================
// DHUUD HSSE Platform - Service Worker
// Version: 2025.01.14.003
// ============================================

// Declare self as ServiceWorkerGlobalScope with extended properties
declare const self: ServiceWorkerGlobalScope & {
  Notification?: {
    permission: NotificationPermission;
  };
};

// Extend NotificationOptions to include vibrate and other SW-specific properties
interface ExtendedNotificationOptions extends NotificationOptions {
  vibrate?: number[];
  actions?: Array<{ action: string; title: string }>;
  badge?: string;
  renotify?: boolean;
}

import { clientsClaim, skipWaiting } from 'workbox-core';
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { NetworkFirst, CacheFirst, StaleWhileRevalidate } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';

const SW_VERSION = '2025.01.18.003';
const CACHE_NAME = `dhuud-cache-v6-${SW_VERSION}`;
const API_CACHE_NAME = `dhuud-api-cache-v3-${SW_VERSION}`;
const STATIC_CACHE_NAME = `dhuud-static-cache-v3-${SW_VERSION}`;
const OFFLINE_URL = '/offline.html';
const SYNC_TAG = 'offline-mutations-sync';
const PERIODIC_SYNC_TAG = 'server-updates-sync';
const MUTATION_STORE_KEY = 'offline-mutation-queue';

// Maximum entries for API cache
const API_CACHE_MAX_ENTRIES = 100;

// Gate-specific API endpoints for enhanced caching
const GATE_API_PATTERNS = [
  '/rest/v1/gate_entry_logs',
  '/rest/v1/security_blacklist',
  '/rest/v1/contractor_access_logs',
  '/rest/v1/geofence_alerts',
];

// HSSE Event Offline Reporting - Essential reference data endpoints
const HSSE_OFFLINE_API_PATTERNS = [
  '/rest/v1/hsse_event_types',
  '/rest/v1/sites',
  '/rest/v1/departments',
  '/rest/v1/buildings',
  '/rest/v1/floors_zones',
  '/rest/v1/asset_categories',
  // Notification matrix and templates for offline preview
  '/rest/v1/incident_notification_matrix',
  '/rest/v1/notification_templates',
];

skipWaiting();
clientsClaim();
cleanupOutdatedCaches();

// Precache assets generated by Vite
// @ts-ignore
precacheAndRoute(self.__WB_MANIFEST);

// -----------------------------------------------------------------------------
// Runtime Caching Logic (Migrated from vite.config.ts and extended)
// -----------------------------------------------------------------------------

// Supabase API
registerRoute(
  /^https:\/\/xdlowvfzhvjzbtgvurzj\.supabase\.co\/rest\/v1\/.*/i,
  new NetworkFirst({
    cacheName: 'supabase-api-cache',
    networkTimeoutSeconds: 10,
    plugins: [
      new ExpirationPlugin({ maxEntries: 200, maxAgeSeconds: 86400 }),
      new CacheableResponsePlugin({ statuses: [0, 200] }),
    ],
  }),
  'GET'
);

// Supabase Storage
registerRoute(
  /^https:\/\/xdlowvfzhvjzbtgvurzj\.supabase\.co\/storage\/v1\/object\/.*/i,
  new CacheFirst({
    cacheName: 'supabase-storage-cache',
    plugins: [
      new ExpirationPlugin({ maxEntries: 100, maxAgeSeconds: 604800 }),
      new CacheableResponsePlugin({ statuses: [0, 200] }),
    ],
  }),
  'GET'
);

// Google Fonts Stylesheets
registerRoute(
  /^https:\/\/fonts\.googleapis\.com\/.*/i,
  new StaleWhileRevalidate({
    cacheName: 'google-fonts-stylesheets',
  }),
  'GET'
);

// Google Fonts Webfonts
registerRoute(
  /^https:\/\/fonts\.gstatic\.com\/.*/i,
  new CacheFirst({
    cacheName: 'google-fonts-webfonts',
    plugins: [
      new ExpirationPlugin({ maxEntries: 30, maxAgeSeconds: 31536000 }),
      new CacheableResponsePlugin({ statuses: [0, 200] }),
    ],
  }),
  'GET'
);

// -----------------------------------------------------------------------------
// Custom Logic from public/sw.js
// -----------------------------------------------------------------------------

// Store notification in history by sending to clients
function storeNotificationInHistory(title: string, body: string, type: string) {
  self.clients.matchAll().then(clients => {
    clients.forEach(client => {
      client.postMessage({
        type: 'STORE_NOTIFICATION',
        notification: { title, body, type }
      });
    });
  });
}

// Show notification for sync results
async function showSyncNotification(result: { success: number; failed: number }) {
  // Check if we have notification permission
  if (self.Notification?.permission !== 'granted') {
    return;
  }

  const { success, failed } = result;
  
  // Don't show notification if nothing happened
  if (success === 0 && failed === 0) {
    return;
  }

  const title = failed > 0 ? 'Sync Partially Failed' : 'Sync Complete';
  const body = failed > 0
    ? `${success} change(s) synced, ${failed} failed`
    : `${success} change(s) synced successfully`;
  const icon = 'https://xdlowvfzhvjzbtgvurzj.supabase.co/storage/v1/object/public/branding/9290e913-c735-405c-91c6-141e966011ae/favicon/1764707368310.png';
  const tag = 'sync-notification';
  const notificationType = failed > 0 ? 'error' : 'sync';

  try {
    await self.registration.showNotification(title, {
      body,
      icon,
      tag,
      badge: 'https://xdlowvfzhvjzbtgvurzj.supabase.co/storage/v1/object/public/branding/9290e913-c735-405c-91c6-141e966011ae/favicon/1764707368310.png',
      vibrate: [100, 50, 100],
      data: { success, failed },
      actions: failed > 0 ? [
        { action: 'retry', title: 'Retry' },
        { action: 'dismiss', title: 'Dismiss' }
      ] : []
    } as ExtendedNotificationOptions);
    
    // Store in notification history
    storeNotificationInHistory(title, body, notificationType);
  } catch (error) {
    console.error('Failed to show notification:', error);
  }
}

// Handle notification click with security-specific actions
self.addEventListener('notificationclick', (event: any) => {
  event.notification.close();

  const notificationData = event.notification.data || {};
  const action = event.action;

  // Handle retry action for sync
  if (action === 'retry') {
    event.waitUntil(processMutationQueue());
    return;
  }

  // Handle update action
  if (action === 'update' || notificationData.type === 'update') {
    event.waitUntil(
      (async () => {
        // @ts-ignore
        if (self.registration.waiting) {
          // @ts-ignore
          self.registration.waiting.postMessage({ type: 'SKIP_WAITING' });
        }
        const cacheNames = await caches.keys();
        await Promise.all(
          cacheNames
            .filter(name => name.startsWith('dhuud-'))
            .map(name => {
              console.log('[SW] Clearing cache for update:', name);
              return caches.delete(name);
            })
        );
        const clients = await self.clients.matchAll({ type: 'window' });
        for (const client of clients) {
          await client.navigate(client.url);
        }
      })()
    );
    return;
  }

  // Handle emergency alert actions
  if (notificationData.type === 'emergency_alert') {
    const alertId = notificationData.alert_id;
    
    if (action === 'acknowledge') {
      // Acknowledge the alert via API call
      event.waitUntil(
        (async () => {
          try {
            // Try to acknowledge via edge function
            const response = await fetch(
              `https://xdlowvfzhvjzbtgvurzj.supabase.co/functions/v1/acknowledge-emergency-alert`,
              {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ alert_id: alertId })
              }
            );
            console.log('[SW] Emergency alert acknowledged:', response.ok);
          } catch (err) {
            console.error('[SW] Failed to acknowledge alert:', err);
          }
          
          // Navigate to alert details
          const clients = await self.clients.matchAll({ type: 'window' });
          const targetUrl = notificationData.action_url || `/security/emergency-alerts?id=${alertId}`;
          if (clients.length > 0) {
            return clients[0].navigate(targetUrl).then((client: any) => client.focus());
          }
          return self.clients.openWindow(targetUrl);
        })()
      );
      return;
    }
    
    if (action === 'view' || !action) {
      // Navigate to emergency alert details
      const targetUrl = notificationData.action_url || `/security/emergency-alerts?id=${alertId}`;
      event.waitUntil(
        self.clients.matchAll({ type: 'window' }).then((clients) => {
          if (clients.length > 0) {
            return clients[0].navigate(targetUrl).then((client: any) => client.focus());
          }
          return self.clients.openWindow(targetUrl);
        })
      );
      return;
    }
    
    if (action === 'map' && notificationData.gps_lat && notificationData.gps_lng) {
      // Open Google Maps with location
      const mapsUrl = `https://maps.google.com/?q=${notificationData.gps_lat},${notificationData.gps_lng}`;
      event.waitUntil(self.clients.openWindow(mapsUrl));
      return;
    }
  }

  // Handle SLA escalation
  if (notificationData.type === 'sla_escalation') {
    event.waitUntil(
      self.clients.matchAll({ type: 'window' }).then((clients) => {
        const url = '/admin/sla-dashboard';
        if (clients.length > 0) {
          return clients[0].navigate(url).then((client: any) => client.focus());
        }
        return self.clients.openWindow(url);
      })
    );
    return;
  }

  // Default: Open or focus the app with action_url if provided
  const targetUrl = notificationData.action_url || '/';
  event.waitUntil(
    self.clients.matchAll({ type: 'window' }).then((clients) => {
      if (clients.length > 0) {
        return clients[0].navigate(targetUrl).then((client: any) => client.focus());
      }
      return self.clients.openWindow(targetUrl);
    })
  );
});

// Show urgent SLA escalation notification
async function showUrgentSLANotification(data: any) {
  if (self.Notification?.permission !== 'granted') {
    return;
  }

  const { title, body, level } = data;
  const notificationTitle = title || '🚨 Critical SLA Escalation';
  const notificationBody = body || 'An action has been escalated and requires immediate attention';

  try {
    await self.registration.showNotification(notificationTitle, {
      body: notificationBody,
      icon: 'https://xdlowvfzhvjzbtgvurzj.supabase.co/storage/v1/object/public/branding/9290e913-c735-405c-91c6-141e966011ae/favicon/1764707368310.png',
      tag: `sla-escalation-${Date.now()}`,
      badge: 'https://xdlowvfzhvjzbtgvurzj.supabase.co/storage/v1/object/public/branding/9290e913-c735-405c-91c6-141e966011ae/favicon/1764707368310.png',
      vibrate: [200, 100, 200, 100, 200],
      requireInteraction: true,
      data: { type: 'sla_escalation', level },
      actions: [
        { action: 'view', title: 'View Dashboard' },
        { action: 'dismiss', title: 'Dismiss' }
      ]
    } as ExtendedNotificationOptions);
    
    storeNotificationInHistory(notificationTitle, notificationBody, 'error');
  } catch (error) {
    console.error('Failed to show urgent SLA notification:', error);
  }
}

// Handle messages from clients including urgent SLA escalation broadcasts
self.addEventListener('message', (event: any) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    // @ts-ignore
    self.skipWaiting();
  }
  
  // Handle manual sync trigger from the app
  if (event.data && event.data.type === 'TRIGGER_SYNC') {
    processMutationQueue().then((result) => {
      // Notify all clients about sync result
      self.clients.matchAll().then((clients) => {
        clients.forEach((client) => {
          client.postMessage({
            type: 'SYNC_COMPLETE',
            success: result.success,
            failed: result.failed,
          });
        });
      });
      
      // Show notification if permission granted
      showSyncNotification(result);
    });
  }
  
  // Handle urgent SLA escalation push from client
  if (event.data && event.data.type === 'SLA_ESCALATION_URGENT') {
    showUrgentSLANotification(event.data);
  }
});

// Push event handler
self.addEventListener('push', (event: any) => {
  if (!event.data) {
    console.log('[SW] Push received but no data');
    return;
  }

  let payload;
  try {
    payload = event.data.json();
  } catch (e) {
    payload = {
      title: 'New Notification',
      body: event.data.text(),
      type: 'info'
    };
  }

  const {
    title = 'DHUUD Platform',
    body = 'You have a new notification',
    icon = 'https://xdlowvfzhvjzbtgvurzj.supabase.co/storage/v1/object/public/branding/9290e913-c735-405c-91c6-141e966011ae/favicon/1764707368310.png',
    badge = 'https://xdlowvfzhvjzbtgvurzj.supabase.co/storage/v1/object/public/branding/9290e913-c735-405c-91c6-141e966011ae/favicon/1764707368310.png',
    tag,
    data = {},
    actions = [],
    requireInteraction = false,
    vibrate = [100, 50, 100],
  } = payload;

  let notificationOptions: any = {
    body,
    icon,
    badge,
    tag: tag || `push-${Date.now()}`,
    data: { ...data, timestamp: Date.now() },
    actions,
    requireInteraction,
    vibrate,
  };

  if (data.type === 'emergency_alert') {
    notificationOptions = {
      ...notificationOptions,
      vibrate: [500, 200, 500, 200, 500, 200, 500, 200, 500],
      requireInteraction: true,
      tag: `emergency-${data.alert_id || Date.now()}`,
      renotify: true,
      actions: [
        { action: 'acknowledge', title: data.lang === 'ar' ? 'إقرار' : 'Acknowledge' },
        { action: 'view', title: data.lang === 'ar' ? 'عرض' : 'View Details' },
        ...(data.gps_lat && data.gps_lng ? [
          { action: 'map', title: data.lang === 'ar' ? '🗺️ خريطة' : '🗺️ Map' }
        ] : [])
      ],
      data: {
        ...data,
        timestamp: Date.now(),
        type: 'emergency_alert',
      },
    };
  }

  if (data.type === 'sla_escalation') {
    notificationOptions = {
      ...notificationOptions,
      vibrate: [200, 100, 200, 100, 200],
      requireInteraction: true,
      tag: `sla-escalation-${data.action_id || Date.now()}`,
      actions: [
        { action: 'view', title: data.lang === 'ar' ? 'عرض' : 'View Dashboard' },
        { action: 'dismiss', title: data.lang === 'ar' ? 'إغلاق' : 'Dismiss' }
      ],
    };
  }

  event.waitUntil(
    self.registration.showNotification(title, notificationOptions).then(() => {
      storeNotificationInHistory(title, body, data.type || 'info');
      
      if (data.type === 'emergency_alert') {
        self.clients.matchAll().then(clients => {
          clients.forEach(client => {
            client.postMessage({
              type: 'EMERGENCY_ALERT_RECEIVED',
              alert: data
            });
          });
        });
      }
    })
  );
});

// Background Sync event handler
self.addEventListener('sync', (event: any) => {
  if (event.tag === SYNC_TAG) {
    event.waitUntil(
      processMutationQueue().then((result) => {
        showSyncNotification(result);
        return result;
      })
    );
  }
  
  if (event.tag === 'area-inspection-sync') {
    event.waitUntil(
      (async () => {
        const clients = await self.clients.matchAll();
        clients.forEach(client => {
          client.postMessage({ type: 'AREA_INSPECTION_SYNC' });
        });
      })()
    );
  }
});

// Periodic Background Sync event handler
self.addEventListener('periodicsync', (event: any) => {
  if (event.tag === PERIODIC_SYNC_TAG) {
    event.waitUntil(checkForServerUpdates());
  }
});

// Check for server updates and notify user
async function checkForServerUpdates() {
  try {
    const response = await fetch('/?_=' + Date.now(), { 
      cache: 'no-store',
      headers: { 'Cache-Control': 'no-cache' }
    });
    
    if (!response.ok) return;

    // @ts-ignore
    const registration = self.registration;
    await registration.update();
    
    if (registration.waiting) {
      await showUpdateNotification();
    }

    const mutationResult = await processMutationQueue();
    if (mutationResult.success > 0 || mutationResult.failed > 0) {
      showSyncNotification(mutationResult);
    }

    const clients = await self.clients.matchAll();
    clients.forEach(client => {
      client.postMessage({
        type: 'PERIODIC_SYNC_COMPLETE',
        timestamp: Date.now(),
        hasUpdate: !!registration.waiting,
      });
    });
  } catch (error) {
    console.error('Periodic sync failed:', error);
  }
}

// Show notification when updates are available
async function showUpdateNotification() {
  if (self.Notification?.permission !== 'granted') {
    return;
  }

  try {
    await self.registration.showNotification('Update Available', {
      body: 'A new version of the app is available. Tap to update.',
      icon: 'https://xdlowvfzhvjzbtgvurzj.supabase.co/storage/v1/object/public/branding/9290e913-c735-405c-91c6-141e966011ae/favicon/1764707368310.png',
      tag: 'update-notification',
      vibrate: [100, 50, 100],
      data: { type: 'update' },
      actions: [
        { action: 'update', title: 'Update Now' },
        { action: 'dismiss', title: 'Later' }
      ]
    } as ExtendedNotificationOptions);
    
    storeNotificationInHistory('Update Available', 'A new version of the app is available.', 'update');
  } catch (error) {
    console.error('Failed to show update notification:', error);
  }
}

// Process queued mutations
async function processMutationQueue() {
  const result = { success: 0, failed: 0 };
  
  try {
    const clients = await self.clients.matchAll();
    if (clients.length === 0) return result;
    
    const client = clients[0];
    
    return new Promise<{ success: number; failed: number }>((resolve) => {
      const messageChannel = new MessageChannel();
      
      messageChannel.port1.onmessage = async (event) => {
        const mutations = event.data.mutations || [];
        
        for (const mutation of mutations) {
          try {
            const response = await executeMutation(mutation);

            if (response.ok) {
              result.success++;
              client.postMessage({ 
                type: 'MUTATION_SUCCESS', 
                id: mutation.id 
              });
            } else if (response.status >= 400 && response.status < 500) {
              result.failed++;
              client.postMessage({
                type: 'MUTATION_FAILED_PERMANENT',
                id: mutation.id,
                error: `Permanent failure: ${response.status} ${response.statusText}`
              });
            } else if (response.status >= 500) {
              result.failed++;
              client.postMessage({
                type: 'MUTATION_FAILED_RETRYABLE',
                id: mutation.id,
                error: `Retryable failure: ${response.status} ${response.statusText}`
              });
            } else {
              result.failed++;
              client.postMessage({
                type: 'MUTATION_FAILED_RETRYABLE',
                id: mutation.id,
                error: `Unknown failure: ${response.status} ${response.statusText}`
              });
            }
          } catch (error: any) {
            result.failed++;
            client.postMessage({
              type: 'MUTATION_FAILED_RETRYABLE',
              id: mutation.id,
              error: `Network/System error: ${error.message}`
            });
          }
        }
        
        resolve(result);
      };
      
      client.postMessage(
        { type: 'GET_MUTATIONS' },
        [messageChannel.port2]
      );
      
      setTimeout(() => resolve(result), 30000);
    });
  } catch (error) {
    console.error('Background sync failed:', error);
    return result;
  }
}

// Execute a single mutation
async function executeMutation(mutation: any) {
  if (!mutation.endpoint) {
    return {
      ok: false,
      status: 400,
      statusText: 'Missing endpoint'
    } as Response;
  }
  
  const response = await fetch(mutation.endpoint, {
    method: mutation.method || 'POST',
    headers: {
      'Content-Type': 'application/json',
      ...mutation.headers,
    },
    body: mutation.body ? JSON.stringify(mutation.body) : undefined,
  });
  
  if (response.ok && mutation.mutationKey) {
    const key = mutation.mutationKey.toLowerCase();
    if (key.includes('incident') || key.includes('observation')) {
      await triggerIncidentNotification(mutation, response.clone());
    }
  }
  
  return response;
}

async function triggerIncidentNotification(mutation: any, response: Response) {
  try {
    const data = await response.json();
    const incidentId = data?.id || data?.data?.id;
    
    if (!incidentId) {
      console.log('[SW] No incident ID found in response, skipping notification');
      return;
    }
    
    // @ts-ignore
    const supabaseUrl = mutation.endpoint?.split('/rest/')[0] || self.SUPABASE_URL || 'https://xdlowvfzhvjzbtgvurzj.supabase.co';
    
    const notifyResponse = await fetch(`${supabaseUrl}/functions/v1/dispatch-incident-notification`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': mutation.headers?.Authorization || mutation.headers?.authorization || '',
      },
      body: JSON.stringify({
        incident_id: incidentId,
        event_type: 'incident_created',
        source: 'offline_sync'
      }),
    });
    
    if (notifyResponse.ok) {
      console.log('[SW] Notification dispatched for synced incident:', incidentId);
    }
  } catch (error) {
    console.error('[SW] Failed to trigger incident notification:', error);
  }
}
