-- Create tenant_document_settings table for centralized document branding
CREATE TABLE public.tenant_document_settings (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  tenant_id uuid REFERENCES public.tenants(id) ON DELETE CASCADE NOT NULL UNIQUE,
  
  -- Header Configuration
  header_logo_position text DEFAULT 'left' CHECK (header_logo_position IN ('left', 'center', 'right')),
  header_text_primary text DEFAULT 'HSSE Department',
  header_text_secondary text,
  header_bg_color text DEFAULT '#ffffff',
  header_text_color text DEFAULT '#1f2937',
  show_logo boolean DEFAULT true,
  
  -- Footer Configuration
  footer_text text DEFAULT 'Confidential - Generated by Dhuud Gatekeeper',
  show_page_numbers boolean DEFAULT true,
  show_date_printed boolean DEFAULT true,
  footer_bg_color text DEFAULT '#f3f4f6',
  footer_text_color text DEFAULT '#6b7280',
  
  -- Watermark
  watermark_text text,
  watermark_enabled boolean DEFAULT false,
  watermark_opacity integer DEFAULT 15 CHECK (watermark_opacity >= 0 AND watermark_opacity <= 100),
  
  -- Timestamps
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.tenant_document_settings ENABLE ROW LEVEL SECURITY;

-- RLS Policy: Users can view their own tenant's document settings
CREATE POLICY "Users can view own tenant document settings"
ON public.tenant_document_settings FOR SELECT
USING (tenant_id = get_auth_tenant_id());

-- RLS Policy: Admins can manage their own tenant's document settings
CREATE POLICY "Admins can manage own tenant document settings"
ON public.tenant_document_settings FOR ALL
USING (tenant_id = get_auth_tenant_id() AND has_role(auth.uid(), 'admin'::app_role));

-- Index for fast tenant lookups
CREATE INDEX idx_tenant_document_settings_tenant ON public.tenant_document_settings(tenant_id);

-- Auto-update timestamp trigger
CREATE TRIGGER update_tenant_document_settings_updated_at
BEFORE UPDATE ON public.tenant_document_settings
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();